import type { ConnectorDefinition, CapabilityGroupMeta } from './types';

/**
 * CONNECTOR_CATALOG — single source of truth for every integration.
 *
 * Rules:
 *  - `id` MUST match the key in the Edge Function PROVIDERS map.
 *  - `capabilities` MUST match the endpoint keys in the Edge Function.
 *  - `auth: 'oauth2'` → `startConnectorOAuth(id)` is called automatically.
 *  - `auth: 'api_key'` → backend reads from Supabase Vault secrets.
 *  - Adding a new provider = add an entry here + add to Edge Function PROVIDERS.
 */
export const CONNECTOR_CATALOG: ConnectorDefinition[] = [
  // ─────────────────────── Communication ───────────────────────
  {
    id: 'gmail',
    name: 'Gmail',
    summary: 'Read, search and send email from your Google account.',
    groups: ['communication'],
    capabilities: ['email.read', 'email.send'],
    roadmap: { v2: ['email.labels'] },
    auth: 'oauth2',
    scopes: ['https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/gmail.send'],
    availability: 'available',
    apiBase: 'https://gmail.googleapis.com/gmail/v1',
    webhooks: true,
    rateLimitPerMinute: 240,
    brandColor: '#EA4335',
    iconCode: 'G',
  },
  {
    id: 'outlook',
    name: 'Outlook / Microsoft 365',
    summary: 'Work mail and contacts from Microsoft 365.',
    groups: ['communication'],
    capabilities: ['email.read', 'email.send', 'contacts.read'],
    auth: 'oauth2',
    scopes: ['offline_access', 'User.Read', 'Mail.Read', 'Mail.Send', 'Contacts.Read'],
    availability: 'available',
    apiBase: 'https://graph.microsoft.com/v1.0',
    webhooks: true,
    rateLimitPerMinute: 180,
    brandColor: '#0078D4',
    iconCode: 'O',
  },
  {
    id: 'imap',
    name: 'IMAP / SMTP',
    summary: 'Connect any mailbox that speaks IMAP and SMTP.',
    groups: ['communication'],
    capabilities: ['email.read', 'email.send'],
    auth: 'imap',
    availability: 'available',
    rateLimitPerMinute: 60,
    brandColor: '#64748B',
    iconCode: 'I',
  },
  {
    id: 'slack',
    name: 'Slack',
    summary: 'Read channels and post messages to your workspace.',
    groups: ['communication'],
    capabilities: ['chat.read', 'chat.send'],
    roadmap: { v2: ['chat.threads'] },
    auth: 'oauth2',
    scopes: ['channels:read', 'channels:history', 'chat:write', 'users:read'],
    availability: 'available',
    apiBase: 'https://slack.com/api',
    webhooks: true,
    rateLimitPerMinute: 60,
    brandColor: '#611F69',
    iconCode: 'Sl',
  },
  {
    id: 'microsoft_teams',
    name: 'Microsoft Teams',
    summary: 'Team chats, channels and messages in one inbox.',
    groups: ['communication'],
    capabilities: ['chat.read', 'chat.send', 'chat.channels'],
    roadmap: { v2: ['chat.threads'] },
    auth: 'oauth2',
    scopes: [
      'offline_access', 'User.Read', 'Chat.Read', 'Chat.ReadWrite',
      'Team.ReadBasic.All', 'Channel.ReadBasic.All', 'ChannelMessage.Read.All',
    ],
    availability: 'available',
    apiBase: 'https://graph.microsoft.com/v1.0',
    rateLimitPerMinute: 120,
    brandColor: '#5059C9',
    iconCode: 'Te',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Business',
    summary: 'Send and receive WhatsApp Business messages inside CHATR.',
    groups: ['communication'],
    capabilities: ['chat.read', 'chat.send'],
    auth: 'api_key',
    availability: 'available',
    apiBase: 'https://graph.facebook.com/v21.0',
    webhooks: true,
    rateLimitPerMinute: 120,
    brandColor: '#25D366',
    iconCode: 'WA',
  },
  {
    id: 'discord',
    name: 'Discord',
    summary: 'Community channels and direct messages.',
    groups: ['communication'],
    capabilities: ['chat.read', 'chat.send'],
    auth: 'oauth2',
    scopes: ['identify', 'guilds', 'messages.read'],
    availability: 'available',
    apiBase: 'https://discord.com/api/v10',
    rateLimitPerMinute: 50,
    brandColor: '#5865F2',
    iconCode: 'Di',
  },

  // ─────────────────────── Calendar & Meetings ───────────────────────
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    summary: 'See and create events across your calendars.',
    groups: ['calendar'],
    capabilities: ['calendar.read', 'calendar.write'],
    auth: 'oauth2',
    scopes: ['https://www.googleapis.com/auth/calendar'],
    availability: 'available',
    apiBase: 'https://www.googleapis.com/calendar/v3',
    webhooks: true,
    rateLimitPerMinute: 240,
    brandColor: '#4285F4',
    iconCode: 'GC',
  },
  {
    id: 'outlook_calendar',
    name: 'Outlook Calendar',
    summary: 'Microsoft 365 calendar and scheduling.',
    groups: ['calendar'],
    capabilities: ['calendar.read', 'calendar.write'],
    auth: 'oauth2',
    scopes: ['offline_access', 'User.Read', 'Calendars.ReadWrite'],
    availability: 'available',
    apiBase: 'https://graph.microsoft.com/v1.0',
    rateLimitPerMinute: 180,
    brandColor: '#0F6CBD',
    iconCode: 'OC',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    summary: 'Create and join meetings without leaving CHATR.',
    groups: ['calendar'],
    capabilities: ['meetings.create', 'meetings.read'],
    auth: 'oauth2',
    scopes: ['meeting:write', 'meeting:read'],
    availability: 'available',
    apiBase: 'https://api.zoom.us/v2',
    rateLimitPerMinute: 60,
    brandColor: '#2D8CFF',
    iconCode: 'Zm',
  },
  {
    id: 'google_meet',
    name: 'Google Meet',
    summary: 'Instant meeting links attached to your events.',
    groups: ['calendar'],
    capabilities: ['meetings.create', 'meetings.read'],
    auth: 'oauth2',
    scopes: ['https://www.googleapis.com/auth/calendar.events'],
    availability: 'available',
    apiBase: 'https://www.googleapis.com/calendar/v3',
    rateLimitPerMinute: 120,
    brandColor: '#00897B',
    iconCode: 'GM',
  },

  // ─────────────────────── Storage ───────────────────────
  {
    id: 'google_drive',
    name: 'Google Drive',
    summary: 'Browse, search and attach your Drive files.',
    groups: ['storage'],
    capabilities: ['files.read', 'files.write'],
    auth: 'oauth2',
    scopes: ['https://www.googleapis.com/auth/drive'],
    availability: 'available',
    apiBase: 'https://www.googleapis.com/drive/v3',
    webhooks: true,
    rateLimitPerMinute: 240,
    brandColor: '#0F9D58',
    iconCode: 'GD',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    summary: 'Microsoft 365 files and shared documents.',
    groups: ['storage'],
    capabilities: ['files.read', 'files.write'],
    auth: 'oauth2',
    scopes: ['offline_access', 'Files.ReadWrite'],
    availability: 'available',
    apiBase: 'https://graph.microsoft.com/v1.0',
    rateLimitPerMinute: 180,
    brandColor: '#0364B8',
    iconCode: 'OD',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    summary: 'Files and folders from your Dropbox account.',
    groups: ['storage'],
    capabilities: ['files.read', 'files.write'],
    auth: 'oauth2',
    scopes: ['files.content.read', 'files.content.write'],
    availability: 'available',
    apiBase: 'https://api.dropboxapi.com/2',
    rateLimitPerMinute: 120,
    brandColor: '#0061FF',
    iconCode: 'Db',
  },

  // ─────────────────────── Professional ───────────────────────
  {
    id: 'linkedin',
    name: 'LinkedIn',
    summary: 'Your professional profile and network.',
    groups: ['professional'],
    capabilities: ['profile.read'],
    roadmap: { v2: ['chat.send'] },
    auth: 'oauth2',
    scopes: ['r_liteprofile', 'r_emailaddress'],
    availability: 'available',
    apiBase: 'https://api.linkedin.com/v2',
    rateLimitPerMinute: 30,
    brandColor: '#0A66C2',
    iconCode: 'Li',
  },
  {
    id: 'github',
    name: 'GitHub',
    summary: 'Repos, issues and reviews in your workflow.',
    groups: ['professional'],
    capabilities: ['code.repos', 'issues.read'],
    roadmap: { v2: ['issues.write'], v3: ['code.reviews'] },
    auth: 'oauth2',
    scopes: ['repo', 'read:user'],
    availability: 'available',
    apiBase: 'https://api.github.com',
    webhooks: true,
    rateLimitPerMinute: 80,
    brandColor: '#24292F',
    iconCode: 'Gh',
  },
  {
    id: 'jira',
    name: 'Jira',
    summary: 'Track and update project issues.',
    groups: ['professional', 'productivity'],
    capabilities: ['issues.read', 'issues.write'],
    auth: 'oauth2',
    scopes: ['read:jira-work', 'write:jira-work', 'offline_access'],
    availability: 'available',
    apiBase: 'https://api.atlassian.com',
    webhooks: true,
    rateLimitPerMinute: 60,
    brandColor: '#0052CC',
    iconCode: 'Ji',
  },
  {
    id: 'confluence',
    name: 'Confluence',
    summary: 'Team knowledge base pages and docs.',
    groups: ['professional', 'productivity'],
    capabilities: ['docs.read', 'docs.write'],
    auth: 'oauth2',
    scopes: ['read:confluence-content.all', 'offline_access'],
    availability: 'available',
    apiBase: 'https://api.atlassian.com',
    rateLimitPerMinute: 60,
    brandColor: '#172B4D',
    iconCode: 'Cf',
  },

  // ─────────────────────── CRM & Sales ───────────────────────
  {
    id: 'salesforce',
    name: 'Salesforce',
    summary: 'Accounts, contacts and deals from your CRM.',
    groups: ['crm'],
    capabilities: ['crm.read', 'crm.write', 'contacts.read'],
    auth: 'oauth2',
    scopes: ['api', 'refresh_token'],
    availability: 'available',
    rateLimitPerMinute: 100,
    brandColor: '#00A1E0',
    iconCode: 'SF',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    summary: 'Contacts, companies and pipeline activity.',
    groups: ['crm'],
    capabilities: ['crm.read', 'crm.write', 'contacts.read'],
    auth: 'oauth2',
    scopes: ['crm.objects.contacts.read', 'crm.objects.deals.read'],
    availability: 'available',
    apiBase: 'https://api.hubapi.com',
    webhooks: true,
    rateLimitPerMinute: 100,
    brandColor: '#FF7A59',
    iconCode: 'Hs',
  },

  // ─────────────────────── Productivity ───────────────────────
  {
    id: 'notion',
    name: 'Notion',
    summary: 'Pages and databases you have shared.',
    groups: ['productivity'],
    capabilities: ['docs.read', 'docs.write', 'tasks.read'],
    auth: 'oauth2',
    availability: 'available',
    apiBase: 'https://api.notion.com/v1',
    rateLimitPerMinute: 60,
    brandColor: '#111111',
    iconCode: 'N',
  },
  {
    id: 'trello',
    name: 'Trello',
    summary: 'Boards, lists and cards as tasks.',
    groups: ['productivity'],
    capabilities: ['tasks.read', 'tasks.write'],
    auth: 'oauth2',
    availability: 'available',
    apiBase: 'https://api.trello.com/1',
    webhooks: true,
    rateLimitPerMinute: 100,
    brandColor: '#0079BF',
    iconCode: 'Tr',
  },
  {
    id: 'asana',
    name: 'Asana',
    summary: 'Projects and tasks with due dates.',
    groups: ['productivity'],
    capabilities: ['tasks.read', 'tasks.write'],
    auth: 'oauth2',
    scopes: ['default'],
    availability: 'available',
    apiBase: 'https://app.asana.com/api/1.0',
    webhooks: true,
    rateLimitPerMinute: 90,
    brandColor: '#F06A6A',
    iconCode: 'As',
  },

  // ─────────────────────── Business ───────────────────────
  {
    id: 'stripe',
    name: 'Stripe',
    summary: 'Payments, customers and payouts.',
    groups: ['business'],
    capabilities: ['payments.read', 'payments.write'],
    auth: 'api_key',
    availability: 'available',
    apiBase: 'https://api.stripe.com/v1',
    webhooks: true,
    rateLimitPerMinute: 100,
    brandColor: '#635BFF',
    iconCode: 'St',
  },
  {
    id: 'razorpay',
    name: 'Razorpay',
    summary: 'UPI and card payments for India.',
    groups: ['business'],
    capabilities: ['payments.read', 'payments.write'],
    auth: 'api_key',
    availability: 'available',
    apiBase: 'https://api.razorpay.com/v1',
    webhooks: true,
    rateLimitPerMinute: 100,
    brandColor: '#0C2451',
    iconCode: 'Rz',
  },
  {
    id: 'google_contacts',
    name: 'Google Contacts',
    summary: 'Sync your address book into CHATR.',
    groups: ['business', 'communication'],
    capabilities: ['contacts.read', 'contacts.write'],
    auth: 'oauth2',
    scopes: ['https://www.googleapis.com/auth/contacts'],
    availability: 'available',
    apiBase: 'https://people.googleapis.com/v1',
    rateLimitPerMinute: 120,
    brandColor: '#1A73E8',
    iconCode: 'GCt',
  },
];

// ─── Group metadata for the UI filter tabs ───────────────────────────────────
export const CAPABILITY_GROUP_META: Record<string, CapabilityGroupMeta> = {
  communication: {
    label: 'Communication',
    description: 'Email, chat and messaging in one inbox',
    capabilities: ['Email', 'Chat', 'Contacts'],
  },
  calendar: {
    label: 'Calendar & Meetings',
    description: 'Availability, events and meeting links',
    capabilities: ['Calendar', 'Meetings'],
  },
  storage: {
    label: 'Files & Storage',
    description: 'Search and attach files from anywhere',
    capabilities: ['Files', 'Documents'],
  },
  professional: {
    label: 'Professional',
    description: 'Code, issues and your professional graph',
    capabilities: ['Repos', 'Issues', 'Profile'],
  },
  crm: {
    label: 'CRM & Sales',
    description: 'Customers, deals and pipeline',
    capabilities: ['CRM', 'Contacts'],
  },
  productivity: {
    label: 'Productivity',
    description: 'Tasks, docs and project boards',
    capabilities: ['Tasks', 'Docs'],
  },
  business: {
    label: 'Business',
    description: 'Payments and business operations',
    capabilities: ['Payments', 'Contacts'],
  },
};

// ─── Helper: map group key → UI display category label ───────────────────────
export const GROUP_TO_CATEGORY: Record<string, string> = {
  communication: 'Messaging & Email',
  calendar: 'Calendar & Meetings',
  storage: 'Files & Storage',
  professional: 'Work & Code',
  crm: 'Customers & Sales',
  productivity: 'Notes & Tasks',
  business: 'Payments & Business',
};
