/**
 * CHATR Simulation Bridge — Types (Gate 8.5)
 * Defines the complete contract between RobotOS and the physics engine.
 * Identical regardless of whether MuJoCo or Isaac Sim is underneath.
 */

export type SimProvenance = 'MUJOCO_PHYSICS' | 'ISAAC_SIM_PHYSICS' | 'STUB_NO_MUJOCO';

export interface SimVector3 {
  x: number;
  y: number;
  z: number;
}

export interface SimQuaternion {
  w: number;
  x: number;
  y: number;
  z: number;
}

export interface SimJointState {
  posRad: number;
  velRadPerSec: number;
  torqueNm: number;
}

export interface SimContact {
  geom_a: string;
  geom_b: string;
  pos: [number, number, number];
  normal_force_N: number;
}

export interface SimImuReading {
  accel: SimVector3;
  gyro: SimVector3;
  noise_sigma: number;
}

/**
 * Complete physics state snapshot.
 * Every field is generated by the physics engine — never synthesized in TypeScript.
 */
export interface SimBridgeState {
  sim_id: string;
  robot_profile_hash: string;
  physics_version: string;           // "mujoco-3.2.4" | "isaac-sim-4.x" | "stub-0.0"
  env_hash: string;
  seed: number;
  timestamp_sim_s: number;
  joint_states: Record<string, SimJointState>;
  base_pose: {
    position: SimVector3;
    orientation: SimQuaternion;
  };
  contacts: SimContact[];
  imu: SimImuReading;
  center_of_mass: SimVector3;
  is_fallen: boolean;
  provenance: SimProvenance;
  camera_rgb_base64: string;         // JPEG, 640x480, from simulated camera
  hand_contact_force_N?: number;     // Physical contact force measured on gripper
  objects?: Record<string, { position: SimVector3; orientation: SimQuaternion }>;
  // Optional fields populated by specific methods:
  navigation_command_acknowledged?: boolean;
  target?: string;
}

export interface SimServerInfo {
  server_version: string;
  physics_version: string;
  profile_hash: string;
  env_hash: string;
  physics_hz: number;
  joint_count: number;
  joint_names: string[];
  provenance: SimProvenance;
  is_mujoco_loaded: boolean;
}

export type SimConnectionState =
  | 'DISCONNECTED'
  | 'CONNECTING'
  | 'CONNECTED'
  | 'RECONNECTING'
  | 'FAILED';

// ── Commands sent to sim-server
export interface SimCommand {
  method:
    | 'ping'
    | 'get_state'
    | 'step'
    | 'reset'
    | 'inject_fault'
    | 'get_server_info'
    | 'navigate';
  params?: Record<string, unknown>;
  id?: number;
}

export type SimFaultType =
  | 'camera_dropout'
  | 'imu_disturbance'
  | 'motor_jam'
  | 'low_friction'
  | 'external_push';

/**
 * The critical guard result.
 * If SIMULATION_AUTHORITY_UNAVAILABLE, motion skills MUST NOT complete.
 */
export type SimGuardResult =
  | 'SIMULATION_AUTHORITY_ONLINE'
  | 'SIMULATION_AUTHORITY_UNAVAILABLE';
