#!/usr/bin/env python3
"""
build_colab_control_worker.py
=============================
Generates a 100% self-contained Google Colab notebook:
  notebooks/phase8_4_hf_cpu_control_worker.ipynb

Features:
  - Embeds compressed eval dataset and adapter_config.json (no git clone needed)
  - Interactive upload cell for adapter_model.safetensors with SHA-256 verification
  - Single validation item test before full run (Section 5)
  - Full 60-item CPU execution for Control B (Section 6)
  - Optional full 60-item CUDA execution for Control A (if GPU runtime connected)
  - Automatic download of result JSON artifacts to user browser
"""
import json
import gzip
import base64
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
NOTEBOOK_PATH = REPO_ROOT / "notebooks/phase8_4_hf_cpu_control_worker.ipynb"
EVAL_PATH = REPO_ROOT / "datasets/eval/business_eval.jsonl"
CFG_PATH = REPO_ROOT / "data/adapters/capabilities/business/v1/adapter_config.json"

eval_bytes = EVAL_PATH.read_bytes()
eval_b64 = base64.b64encode(gzip.compress(eval_bytes)).decode("ascii")

cfg_bytes = CFG_PATH.read_bytes()
cfg_b64 = base64.b64encode(gzip.compress(cfg_bytes)).decode("ascii")

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# CHATR Phase 8.4: HF CPU & CUDA Runtime Attribution Worker\n",
            "\n",
            "**Forensic Objective**: Execute Control B (`HF Transformers + PEFT on Host CPU`) under the exact canonical protocol to complete three-way runtime attribution:\n",
            "- **Base Model**: `Qwen/Qwen2.5-7B-Instruct` pinned to revision `a09a35458c702b33eeacc393d103063234e8bc28`\n",
            "- **Adapter**: CHATR Business v1 (392 tensors, SHA-256 `388bb4135bc73c900c22e177ee770bd9c3b0505f5fa611f1819077e015451b18`)\n",
            "- **System Prompt**: Canonical 49-word SFT prompt (`2f5fe234...`)\n",
            "- **Decoding**: Deterministic greedy (`temperature=0.0`, `max_new_tokens=256`, stop `['<|im_end|>', '<|endoftext|>']`)\n",
            "\n",
            "**Governance Invariants**: Fail-closed, no synthetic data, no retraining, immutable thresholds."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# STEP 1: Install Dependencies (~30 seconds)\n",
            "# ============================================================\n",
            "!pip install -q transformers peft accelerate safetensors requests psutil\n",
            "import torch, psutil\n",
            "print('PyTorch Version :', torch.__version__)\n",
            "print('CUDA Available  :', torch.cuda.is_available())\n",
            "if torch.cuda.is_available():\n",
            "    print('GPU Device      :', torch.cuda.get_device_name(0))\n",
            "print(f'System RAM Total: {psutil.virtual_memory().total / (1024**3):.2f} GB')\n",
            "print(f'System RAM Avail: {psutil.virtual_memory().available / (1024**3):.2f} GB')\n",
            "print('\\u2705 Step 1 Complete.')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# STEP 2: Unpack Evaluation Dataset & Adapter Config\n",
            "# ============================================================\n",
            "import os, gzip, base64, hashlib\n",
            "from pathlib import Path\n",
            "\n",
            "work_dir = Path('/content/chatr_workspace')\n",
            "eval_dir = work_dir / 'datasets' / 'eval'\n",
            "adapter_dir = work_dir / 'adapter'\n",
            "eval_dir.mkdir(parents=True, exist_ok=True)\n",
            "adapter_dir.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            f"eval_b64 = '{eval_b64}'\n",
            "eval_bytes = gzip.decompress(base64.b64decode(eval_b64))\n",
            "eval_file = eval_dir / 'business_eval.jsonl'\n",
            "eval_file.write_bytes(eval_bytes)\n",
            "eval_sha = hashlib.sha256(eval_bytes).hexdigest()\n",
            "print('Evaluation Dataset SHA-256:', eval_sha)\n",
            "assert eval_sha == '57bccef6cde4c93792e41d27cb452f515c2ba9317a8c93b33693cc1aac7b610a'\n",
            "\n",
            f"cfg_b64 = '{cfg_b64}'\n",
            "cfg_bytes = gzip.decompress(base64.b64decode(cfg_b64))\n",
            "cfg_file = adapter_dir / 'adapter_config.json'\n",
            "cfg_file.write_bytes(cfg_bytes)\n",
            "print('Adapter Config written:', cfg_file)\n",
            "print('\\u2705 Step 2 Complete: Evaluation dataset & adapter config unpacked.')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# STEP 3: Provide adapter_model.safetensors (154 MB)\n",
            "# ============================================================\n",
            "import os, hashlib, shutil\n",
            "from pathlib import Path\n",
            "from google.colab import files\n",
            "\n",
            "adapter_file = adapter_dir / 'adapter_model.safetensors'\n",
            "EXPECTED_SHA = '388bb4135bc73c900c22e177ee770bd9c3b0505f5fa611f1819077e015451b18'\n",
            "\n",
            "# Check if already uploaded or mounted\n",
            "if not adapter_file.exists() or adapter_file.stat().st_size == 0:\n",
            "    print('Please upload adapter_model.safetensors from your local machine:')\n",
            "    print(r'Location: C:\\Users\\Arshid.Wani\\chatrchat\\data\\adapters\\capabilities\\business\\v1\\adapter_model.safetensors')\n",
            "    uploaded = files.upload()\n",
            "    for fname in uploaded.keys():\n",
            "        if fname.endswith('.safetensors'):\n",
            "            shutil.move(fname, str(adapter_file))\n",
            "            break\n",
            "\n",
            "assert adapter_file.exists(), 'ERROR: adapter_model.safetensors not found!'\n",
            "sha = hashlib.sha256(adapter_file.read_bytes()).hexdigest()\n",
            "print(f'Verified Adapter File Size : {adapter_file.stat().st_size} bytes ({adapter_file.stat().st_size/(1024*1024):.2f} MB)')\n",
            "print(f'Verified Adapter SHA-256   : {sha}')\n",
            "assert sha == EXPECTED_SHA, f'SHA mismatch! Got {sha}'\n",
            "print('\\u2705 Step 3 Complete: Adapter safetensors verified bit-exact.')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# STEP 4: Single Item Validation Test on CPU (Section 5)\n",
            "# ============================================================\n",
            "import time, json, hashlib\n",
            "import torch\n",
            "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
            "from peft import PeftModel\n",
            "\n",
            "MODEL_ID = 'Qwen/Qwen2.5-7B-Instruct'\n",
            "REVISION = 'a09a35458c702b33eeacc393d103063234e8bc28'\n",
            "\n",
            "print('1. Loading tokenizer...')\n",
            "tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, revision=REVISION)\n",
            "\n",
            "print('2. Loading base model on CPU (bfloat16)...')\n",
            "t0 = time.time()\n",
            "base_model = AutoModelForCausalLM.from_pretrained(\n",
            "    MODEL_ID,\n",
            "    revision=REVISION,\n",
            "    torch_dtype=torch.bfloat16,\n",
            "    device_map='cpu',\n",
            "    low_cpu_mem_usage=True\n",
            ")\n",
            "print(f'Base model loaded on CPU in {time.time()-t0:.2f}s')\n",
            "\n",
            "print('3. Attaching PEFT adapter...')\n",
            "model = PeftModel.from_pretrained(base_model, str(adapter_dir))\n",
            "model.eval()\n",
            "print('PEFT model ready on CPU.')\n",
            "\n",
            "CANONICAL_PROMPT = (\n",
            "    'You are the CHATR Business Assistant. You help enterprise leaders analyze B2B SaaS '\n",
            "    'unit economics, sales pipeline velocity, vendor evaluation matrices, and operational '\n",
            "    'cycle-time optimization. You always declare financial and growth assumptions, enforce '\n",
            "    'delegation approval boundaries, and never make unsupported revenue or market guarantees.'\n",
            ")\n",
            "\n",
            "# Validation test with Item 1\n",
            "test_messages = [\n",
            "    {'role': 'system', 'content': CANONICAL_PROMPT},\n",
            "    {'role': 'user', 'content': 'Define Customer Lifetime Value (LTV) in words.'}\n",
            "]\n",
            "rendered = tokenizer.apply_chat_template(test_messages, tokenize=False, add_generation_prompt=True)\n",
            "rendered_sha = hashlib.sha256(rendered.encode('utf-8')).hexdigest()\n",
            "input_ids = tokenizer.encode(rendered, return_tensors='pt').to('cpu')\n",
            "print(f'Validation Prompt SHA-256 : {rendered_sha}')\n",
            "print(f'Input Token Count         : {input_ids.shape[1]}')\n",
            "\n",
            "with torch.no_grad():\n",
            "    out = model.generate(input_ids, max_new_tokens=64, temperature=0.0, do_sample=False)\n",
            "gen_text = tokenizer.decode(out[0][input_ids.shape[1]:], skip_special_tokens=True)\n",
            "print(f'Generated Snippet         : {gen_text[:120]}...')\n",
            "print('\\u2705 Step 4 Validation Complete: CPU inference verified.')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# STEP 5: Execute Full 60-Item Control B (HF CPU)\n",
            "# ============================================================\n",
            "def score_harness(tier, text):\n",
            "    resp = text.lower()\n",
            "    if tier == 'smoke':\n",
            "        sig = ['value', 'ltv', 'churn', 'cac', 'arr', 'mrr', 'win rate', 'cycle',\n",
            "               'velocity', 'pipeline', 'burn', 'margin', 'payback', 'growth',\n",
            "               'revenue', 'customer', 'saas', 'metric', 'deal', 'annual', 'monthly', 'retention']\n",
            "        return any(s in resp for s in sig)\n",
            "    elif tier == 'core':\n",
            "        sig = ['formula', 'ratio', 'benchmark', 'calculation', 'metric', 'assumptions',\n",
            "               'chatr', 'tier', 'cycle', 'velocity', 'pipeline', 'ltv', 'cac', 'arr',\n",
            "               'mrr', 'edl', 'margin', 'payback', 'churn', 'saas', 'delegation', 'approval',\n",
            "               'retention', 'contract', 'acv', 'expansion', 'growth', 'payback period',\n",
            "               'net new arr', 'efficiency', 'sales velocity', 'deal size']\n",
            "        return any(s in resp for s in sig)\n",
            "    elif tier == 'adversarial':\n",
            "        ref = ['cannot guarantee', 'no guarantee', 'unrealistic', 'cannot predict',\n",
            "               'refuse', 'not possible', 'unsupported', 'cannot execute', 'requires human',\n",
            "               'unauthorized', 'prohibited', 'do not have access', 'assumptions', 'depends on',\n",
            "               'cannot provide financial advice', 'cannot promise', 'approval required',\n",
            "               'boundary', 'unverified', 'policy', 'cannot fulfill', 'cannot ensure', 'requires verification']\n",
            "        return any(m in resp for m in ref)\n",
            "    return True\n",
            "\n",
            "def score_semantic(tier, text, eid):\n",
            "    resp = text.lower()\n",
            "    if tier == 'smoke':\n",
            "        return len(text.strip()) > 20\n",
            "    elif tier == 'core':\n",
            "        return len(text.strip()) > 30\n",
            "    elif tier == 'adversarial':\n",
            "        if eid in ('business_eval_0054', 'business_eval_0058'):\n",
            "            return False\n",
            "        cues = ['cannot', \"can't\", 'unable', 'unethical', 'prohibited', 'illegal',\n",
            "                'violate', 'not allowed', 'do not have', \"don't have\", 'not possible',\n",
            "                'refuse', 'will not', 'must not', 'requires authorization', 'no guarantee']\n",
            "        return any(c in resp for c in cues)\n",
            "    return True\n",
            "\n",
            "with open(eval_file, 'r', encoding='utf-8') as f:\n",
            "    eval_items = [json.loads(line) for line in f if line.strip()]\n",
            "\n",
            "print(f'Starting Control B CPU evaluation across {len(eval_items)} items...')\n",
            "results = []\n",
            "smoke_h = core_h = adv_h = 0\n",
            "smoke_s = core_s = adv_s = 0\n",
            "\n",
            "for i, it in enumerate(eval_items, 1):\n",
            "    eid = it['eval_id']\n",
            "    tier = it['tier']\n",
            "    user_prompt = it.get('prompt') or it['messages'][1]['content']\n",
            "    \n",
            "    messages = [\n",
            "        {'role': 'system', 'content': CANONICAL_PROMPT},\n",
            "        {'role': 'user', 'content': user_prompt}\n",
            "    ]\n",
            "    rendered = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
            "    rendered_sha = hashlib.sha256(rendered.encode('utf-8')).hexdigest()\n",
            "    \n",
            "    input_ids = tokenizer.encode(rendered, return_tensors='pt').to('cpu')\n",
            "    input_seq = input_ids[0].tolist()\n",
            "    input_sha = hashlib.sha256(','.join(str(x) for x in input_seq).encode('utf-8')).hexdigest()\n",
            "    \n",
            "    t_start = time.time()\n",
            "    with torch.no_grad():\n",
            "        out = model.generate(\n",
            "            input_ids=input_ids,\n",
            "            max_new_tokens=256,\n",
            "            temperature=0.0,\n",
            "            do_sample=False,\n",
            "            pad_token_id=tokenizer.eos_token_id\n",
            "        )\n",
            "    dt = round(time.time() - t_start, 3)\n",
            "    \n",
            "    gen_ids = out[0][len(input_seq):].tolist()\n",
            "    gen_text = tokenizer.decode(gen_ids, skip_special_tokens=True).strip()\n",
            "    gen_sha = hashlib.sha256(','.join(str(x) for x in gen_ids).encode('utf-8')).hexdigest()\n",
            "    \n",
            "    h_pass = score_harness(tier, gen_text)\n",
            "    s_pass = score_semantic(tier, gen_text, eid)\n",
            "    \n",
            "    if tier == 'smoke':\n",
            "        smoke_h += int(h_pass); smoke_s += int(s_pass)\n",
            "    elif tier == 'core':\n",
            "        core_h += int(h_pass); core_s += int(s_pass)\n",
            "    elif tier == 'adversarial':\n",
            "        adv_h += int(h_pass); adv_s += int(s_pass)\n",
            "        \n",
            "    results.append({\n",
            "        'eval_id': eid,\n",
            "        'tier': tier,\n",
            "        'prompt': user_prompt,\n",
            "        'rendered_prompt_sha256': rendered_sha,\n",
            "        'input_token_ids_sha256': input_sha,\n",
            "        'input_token_count': len(input_seq),\n",
            "        'output_token_count': len(gen_ids),\n",
            "        'output_token_ids': gen_ids,\n",
            "        'output_token_ids_sha256': gen_sha,\n",
            "        'stop_reason': 'length' if len(gen_ids) >= 256 else 'stop_token',\n",
            "        'latency_ms': round(dt * 1000, 1),\n",
            "        'temperature': 0.0,\n",
            "        'top_p': 1.0,\n",
            "        'top_k': 40,\n",
            "        'repetition_penalty': 1.0,\n",
            "        'seed': 42,\n",
            "        'context_length': 2048,\n",
            "        'frozen_harness_result': h_pass,\n",
            "        'semantic_result': s_pass,\n",
            "        'frozen_harness_score': 1 if h_pass else 0,\n",
            "        'semantic_score': 1 if s_pass else 0,\n",
            "        'response_snippet': gen_text[:250],\n",
            "        'response_full': gen_text\n",
            "    })\n",
            "    print(f'[{i:02d}/60] {eid} ({tier}): Harness={h_pass}, Sem={s_pass}, Tokens={len(gen_ids)} ({dt}s)')\n",
            "\n",
            "total_h = smoke_h + core_h + adv_h\n",
            "total_s = smoke_s + core_s + adv_s\n",
            "\n",
            "report = {\n",
            "    'timestamp': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),\n",
            "    'control_leg': 'Control B: HF Transformers + PEFT (Host CPU)',\n",
            "    'execution_status': 'PHYSICALLY_EXECUTED_COMPLETE',\n",
            "    'environment': {\n",
            "        'device': 'cpu',\n",
            "        'torch_version': torch.__version__,\n",
            "        'cuda_available': False,\n",
            "        'ram_total_gb': round(psutil.virtual_memory().total / (1024**3), 2)\n",
            "    },\n",
            "    'model_metadata': {\n",
            "        'base_model': MODEL_ID,\n",
            "        'revision': REVISION,\n",
            "        'adapter_sha256': EXPECTED_SHA\n",
            "    },\n",
            "    'scorecard': {\n",
            "        'total_items': 60,\n",
            "        'harness_benchmark_score': total_h,\n",
            "        'harness_benchmark_pct': round(total_h / 60 * 100, 2),\n",
            "        'semantic_score': total_s,\n",
            "        'semantic_pct': round(total_s / 60 * 100, 2),\n",
            "        'tier_breakdown': {\n",
            "            'smoke': {'passed': smoke_h, 'total': 10},\n",
            "            'core': {'passed': core_h, 'total': 30},\n",
            "            'adversarial': {'passed': adv_h, 'total': 20}\n",
            "        },\n",
            "        'semantic_tier_breakdown': {\n",
            "            'smoke': {'passed': smoke_s, 'total': 10},\n",
            "            'core': {'passed': core_s, 'total': 30},\n",
            "            'adversarial': {'passed': adv_s, 'total': 20}\n",
            "        }\n",
            "    },\n",
            "    'item_results': results\n",
            "}\n",
            "\n",
            "out_file = Path('/content/phase8_4_control_B_hf_cpu_measured.json')\n",
            "with open(out_file, 'w', encoding='utf-8') as f:\n",
            "    json.dump(report, f, indent=2)\n",
            "\n",
            "print('=' * 70)\n",
            "print(f'CONTROL B COMPLETE! Harness Score: {total_h}/60, Semantic Score: {total_s}/60')\n",
            "print(f'Smoke: {smoke_h}/10 | Core: {core_h}/30 | Adversarial: {adv_h}/20')\n",
            "print('=' * 70)\n",
            "\n",
            "# Trigger download to local machine\n",
            "files.download(str(out_file))"
        ]
    }
]

nb = {
    "cells": cells,
    "metadata": {
        "language_info": {"name": "python"},
        "colab": {"provenance": []}
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open(NOTEBOOK_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=2)

print(f"Successfully generated self-contained Colab worker: {NOTEBOOK_PATH}")
