import React from 'react';

export const MissionControl: React.FC = () => {
  return (
    <div className="bg-black/40 backdrop-blur-md border border-white/10 rounded-xl p-6">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-xl font-semibold text-white">Mission Command</h3>
        <span className="px-3 py-1 bg-red-500/20 text-red-400 rounded-full text-xs font-medium border border-red-500/30">
          Requires Approval
        </span>
      </div>
      
      <div className="space-y-4">
        <div className="bg-white/5 border border-white/10 rounded-lg p-4">
          <div className="flex justify-between items-start mb-3">
            <div>
              <h4 className="text-lg font-medium text-white">Legal Contract Discrepancy</h4>
              <p className="text-sm text-gray-400 mt-1">Generated by InferenceEngine</p>
            </div>
            <span className="text-xl font-bold text-green-400">95% Conf</span>
          </div>
          
          <div className="bg-black/50 rounded p-3 mb-4 text-sm text-gray-300 font-mono">
            <span className="text-purple-400">Action:</span> Trigger HR PagerDuty Alert<br/>
            <span className="text-blue-400">Context:</span> Unapproved indemnity clause identified.
          </div>

          <div className="flex space-x-3">
            <button className="flex-1 bg-green-500 hover:bg-green-600 text-white py-2 rounded font-medium transition-colors">
              Approve Mission
            </button>
            <button className="flex-1 bg-red-500 hover:bg-red-600 text-white py-2 rounded font-medium transition-colors">
              Reject
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
