/**
 * CHATR Central Copy System (UI_COPY)
 * Standardized customer-facing text across the CHATR platform.
 * Enforces CEFR B1-B2 simple, natural, user-driven English.
 */

export const UI_COPY = {
  navigation: {
    home: "Home",
    messages: "Messages",
    ai: "AI",
    business: "Business",
    me: "Me",
    customers: "Customers",
    tasks: "Tasks",
    automations: "Automations",
    connections: "Connections",
    settings: "Settings",
    help: "Help",
  },
  buttons: {
    send: "Send",
    run: "Run",
    setup: "Set up",
    add: "Add",
    getStarted: "Get started",
    continue: "Continue",
    stop: "Stop",
    turnOff: "Turn off",
    tryAgain: "Try again",
    reconnect: "Reconnect",
    disconnect: "Disconnect",
    cancel: "Cancel",
    save: "Save",
    back: "Back",
  },
  onboarding: {
    welcomeTitle: "Welcome to CHATR",
    welcomeSubtitle: "What would you like to do today?",
    goals: {
      talkCustomers: "Talk to customers",
      manageBusiness: "Manage my business",
      findCustomers: "Find new customers",
      manageWhatsapp: "Manage WhatsApp messages",
      automateTasks: "Automate repetitive work",
      useAi: "Use AI to help me",
      connectTools: "Connect my existing tools",
    },
  },
  automations: {
    title: "Automations",
    subtitle: "Let CHATR handle repetitive work automatically.",
    createTask: "Create an automated task",
    searchPlaceholder: "Search automated tasks...",
    emptyStateTitle: "No automated tasks yet",
    emptyStateDesc: "Let CHATR handle repetitive work for you.",
    triggerHeader: "When this happens",
    actionHeader: "CHATR will",
    deleteConfirmation: "Are you sure you want to delete this automated task?",
    taskStartedToast: "Task started.",
    taskPausedToast: "Task paused.",
    taskActivatedToast: "Task activated.",
  },
  connections: {
    title: "Connections",
    subtitle: "Connect WhatsApp, email, and other services to manage all conversations in one place.",
    connectedStatus: "Connected — messages are coming into CHATR.",
    disconnectedStatus: "Not connected. Tap to connect.",
    reconnectBanner: "Your connection needs attention.",
    openingLogin: "Opening sign-in page in your browser...",
  },
  ai: {
    assistantName: "CHATR AI Assistant",
    placeholder: "Ask CHATR anything...",
    workingState: "I'm working on it...",
    findingOptions: "Finding the best options...",
    checkingMessages: "Checking your messages...",
    updatingInfo: "Updating your information...",
    doneState: "Done.",
    doneMessageSent: "Done — your message has been sent.",
    needMoreInfo: "I need a little more information.",
    serviceUnavailable: "That service isn't responding right now.",
    agentsTitle: "AI Assistants",
    agentsSubtitle: "Choose an AI assistant to help with your work.",
    capabilitiesTitle: "What your AI assistant can do",
  },
  errors: {
    genericTitle: "Something went wrong",
    genericBody: "Something went wrong on our side. Please try again.",
    authFailed: "We couldn't sign you in. Please try again.",
    sessionExpired: "Your sign-in has expired. Please sign in again.",
    connectionExpired: "Your connection needs attention. Please reconnect.",
    unrecognizedDevice: "We don't recognize this device.",
    accessDenied: "You don't have access to this.",
    timeout: "That took too long. Please try again.",
  },
  notifications: {
    tokenPausedTitle: "Notifications are paused",
    tokenPausedBody: "Notifications aren't reaching this device right now.",
    taskStarted: "Task started.",
    infoUpdated: "Your information is up to date.",
  },
  emptyStates: {
    noCustomersTitle: "No customers yet",
    noCustomersBody: "Add your first customer to keep conversations and customer details together.",
    noCustomersButton: "Add customer",
    noTasksTitle: "No tasks yet",
    noTasksBody: "Create a task to let CHATR help manage your work.",
    noTasksButton: "Create a task",
  },
  settings: {
    title: "Settings",
    myAccount: "My Account",
    business: "Business",
    messaging: "Messaging",
    aiPreferences: "AI Preferences",
    privacySecurity: "Privacy & Security",
    connections: "Connections",
  }
} as const;
