const CITIES = [
  // ─── UAE ──────────────────────────────────────────────────────────────────
  ['Dubai','UAE','Middle East Tech & Financial Capital'],
  ['Abu Dhabi','UAE','UAE Capital & Government Innovation Hub'],
  ['Sharjah','UAE','UAE Industrial & Education Hub'],
  ['Ajman','UAE','UAE Northern Emirate Commerce Hub'],
  ['Ras Al Khaimah','UAE','UAE Free Zone & Industrial Hub'],
  ['Fujairah','UAE','UAE East Coast Maritime Hub'],
  ['Umm Al Quwain','UAE','UAE Northern Emirate Hub'],
  ['Al Ain','UAE','UAE Garden City & Technology Hub'],

  // ─── SAUDI ARABIA ─────────────────────────────────────────────────────────
  ['Riyadh','Saudi Arabia','KSA Vision 2030 Enterprise Capital'],
  ['Jeddah','Saudi Arabia','Red Sea Commerce & Trade Hub'],
  ['Dammam','Saudi Arabia','Eastern Province Industrial Hub'],
  ['Mecca','Saudi Arabia','Holy City & Religious Services Hub'],
  ['Medina','Saudi Arabia','Islamic Heritage & Logistics Hub'],
  ['Khobar','Saudi Arabia','Aramco Corridor Business Hub'],
  ['Taif','Saudi Arabia','KSA Western Region Commerce Hub'],
  ['Tabuk','Saudi Arabia','NEOM Corridor & Northern Hub'],
  ['Buraidah','Saudi Arabia','Qassim Region Commerce Hub'],
  ['Abha','Saudi Arabia','Asir Region Commercial Center'],
  ['Khamis Mushait','Saudi Arabia','Southern KSA Commerce Hub'],
  ['Hail','Saudi Arabia','Hail Region Trade Hub'],
  ['Najran','Saudi Arabia','Southern Border Commerce Hub'],
  ['Jubail','Saudi Arabia','Industrial City & Petrochemical Hub'],
  ['Yanbu','Saudi Arabia','Red Sea Industrial & Port City'],
  ['Dhahran','Saudi Arabia','KSA Oil Capital & ARAMCO Hub'],
  ['Buraydah','Saudi Arabia','Al-Qassim Commerce Hub'],

  // ─── GCC & LEVANT ─────────────────────────────────────────────────────────
  ['Doha','Qatar','Gulf Enterprise & Energy Capital'],
  ['Al Wakrah','Qatar','Qatar Southern Commerce Hub'],
  ['Al Khor','Qatar','Qatar Northern Industrial Hub'],
  ['Muscat','Oman','Gulf Trade & Logistics Capital'],
  ['Sohar','Oman','Northern Oman Industrial Port'],
  ['Salalah','Oman','Southern Oman Commerce Hub'],
  ['Nizwa','Oman','Oman Interior Heritage Hub'],
  ['Sur','Oman','Oman Eastern Maritime Hub'],
  ['Kuwait City','Kuwait','Gulf Commercial & Financial District'],
  ['Hawalli','Kuwait','Kuwait Commerce District'],
  ['Salmiya','Kuwait','Kuwait Shopping & Commerce Hub'],
  ['Manama','Bahrain','Fintech & Financial Island Hub'],
  ['Riffa','Bahrain','Bahrain Southern Commerce Hub'],
  ['Muharraq','Bahrain','Bahrain Industrial & Trade Hub'],
  ['Amman','Jordan','Levant Business & Technology Hub'],
  ['Zarqa','Jordan','Jordan Industrial Commerce Hub'],
  ['Irbid','Jordan','Northern Jordan University Hub'],
  ['Aqaba','Jordan','Jordan Red Sea Port Hub'],
  ['Beirut','Lebanon','Mediterranean Commerce & Finance Hub'],
  ['Tripoli LB','Lebanon','Northern Lebanon Commerce City'],
  ['Baghdad','Iraq','Iraq Capital Commerce Hub'],
  ['Basra','Iraq','Iraq Southern Port & Oil Hub'],
  ['Erbil','Iraq','Kurdistan Regional Commerce Hub'],
  ['Najaf','Iraq','Iraq Religious Commerce Hub'],
  ['Mosul','Iraq','Iraq Northern Commerce Hub'],
  ['Sulaymaniyah','Iraq','Kurdistan Commerce Hub'],

  // ─── NORTH AFRICA & TURKEY ────────────────────────────────────────────────
  ['Cairo','Egypt','North Africa Commercial Capital'],
  ['Alexandria','Egypt','Mediterranean Port & Business Hub'],
  ['Giza','Egypt','Greater Cairo Commerce District'],
  ['Sharm El Sheikh','Egypt','Red Sea Tourism Hub'],
  ['Luxor','Egypt','Upper Nile Commerce Hub'],
  ['Aswan','Egypt','Southern Egypt Commerce Hub'],
  ['Suez','Egypt','Canal Commerce Hub'],
  ['Casablanca','Morocco','North Africa Financial Capital'],
  ['Rabat','Morocco','Morocco Capital Commerce Hub'],
  ['Marrakech','Morocco','Morocco Tourism & Business Hub'],
  ['Fez','Morocco','Morocco Heritage & Commerce City'],
  ['Tangier','Morocco','Morocco Northern Port Gateway'],
  ['Agadir','Morocco','Morocco Souss Commerce Hub'],
  ['Meknes','Morocco','Morocco Commerce Hub'],
  ['Tunis','Tunisia','Maghreb Commerce & Tech Hub'],
  ['Sfax','Tunisia','Tunisia Southern Commerce Hub'],
  ['Sousse','Tunisia','Tunisia Tourism Commerce Hub'],
  ['Bizerte','Tunisia','Tunisia Northern Port Hub'],
  ['Algiers','Algeria','Algeria Capital Commerce Hub'],
  ['Oran','Algeria','Algeria Western Commerce Hub'],
  ['Constantine','Algeria','Algeria Eastern Commerce Hub'],
  ['Annaba','Algeria','Algeria Port Commerce Hub'],
  ['Tripoli LY','Libya','Libya Capital Commerce Hub'],
  ['Benghazi','Libya','Libya Eastern Commerce Hub'],
  ['Istanbul','Turkey','Eurasian Commerce & Logistics Bridge'],
  ['Ankara','Turkey','Turkish Capital Enterprise Hub'],
  ['Izmir','Turkey','Turkey Aegean Commerce Hub'],
  ['Bursa','Turkey','Turkey Automotive & Industry Hub'],
  ['Antalya','Turkey','Turkey Tourism & Commerce Hub'],
  ['Adana','Turkey','Turkey Southern Commerce City'],
  ['Konya','Turkey','Turkey Central Commerce Hub'],
  ['Gaziantep','Turkey','Turkey Southeast Commerce Hub'],
  ['Kayseri','Turkey','Turkey Central Commerce Hub'],
  ['Mersin','Turkey','Turkey Mediterranean Port Hub'],
  ['Tehran','Iran','Persian Commerce & Enterprise Capital'],
  ['Mashhad','Iran','Iran Eastern Commerce Hub'],
  ['Isfahan','Iran','Iran Cultural & Industrial Hub'],
  ['Tabriz','Iran','Iran Northwest Commerce Hub'],
  ['Shiraz','Iran','Iran Cultural Commerce Hub'],
  ['Karachi','Pakistan','South Asia Commercial Port Capital'],
  ['Lahore','Pakistan','Pakistan Technology & Cultural Hub'],
  ['Islamabad','Pakistan','Pakistan Capital Tech Hub'],
  ['Faisalabad','Pakistan','Pakistan Textile Industrial Hub'],
  ['Rawalpindi','Pakistan','Pakistan Northern Commerce Hub'],
  ['Peshawar','Pakistan','Pakistan Northwestern Commerce Hub'],
  ['Quetta','Pakistan','Pakistan Western Commerce Hub'],
  ['Multan','Pakistan','Pakistan South Punjab Commerce Hub'],
  ['Hyderabad PK','Pakistan','Pakistan Sindh Commerce Hub'],
  ['Gujranwala','Pakistan','Pakistan Commerce Hub'],

  // ─── SOUTHEAST ASIA ───────────────────────────────────────────────────────
  ['Singapore','Singapore','APAC Tech & Financial Hub'],
  ['Kuala Lumpur','Malaysia','ASEAN Business & Digital Capital'],
  ['Penang','Malaysia','Northern Malaysia Tech & Manufacturing'],
  ['Johor Bahru','Malaysia','Malaysia-Singapore Gateway Hub'],
  ['Ipoh','Malaysia','Malaysia Central Commerce Hub'],
  ['Kota Kinabalu','Malaysia','East Malaysia Sabah Capital'],
  ['Kuching','Malaysia','Sarawak Regional Capital'],
  ['Malacca','Malaysia','Malaysia Heritage & Commerce Hub'],
  ['Shah Alam','Malaysia','Selangor Industrial Commerce Hub'],
  ['Petaling Jaya','Malaysia','Greater KL Business Suburb'],
  ['Seremban','Malaysia','Negeri Sembilan Commerce Hub'],
  ['Alor Setar','Malaysia','Malaysia Northern Commerce Hub'],
  ['Kota Bharu','Malaysia','Malaysia Northeast Commerce Hub'],
  ['Kuala Terengganu','Malaysia','Malaysia East Coast Hub'],
  ['Jakarta','Indonesia','Southeast Asia Commerce Capital'],
  ['Surabaya','Indonesia','East Java Industrial Capital'],
  ['Bandung','Indonesia','Indonesia Startup & Creative Hub'],
  ['Medan','Indonesia','North Sumatra Commerce Capital'],
  ['Semarang','Indonesia','Central Java Commerce Hub'],
  ['Makassar','Indonesia','Eastern Indonesia Commerce Gateway'],
  ['Palembang','Indonesia','South Sumatra Commerce Hub'],
  ['Tangerang','Indonesia','Greater Jakarta West Suburb'],
  ['Depok','Indonesia','Greater Jakarta South Hub'],
  ['Yogyakarta','Indonesia','Indonesia Education & Cultural Hub'],
  ['Pontianak','Indonesia','Indonesia Borneo Commerce Hub'],
  ['Samarinda','Indonesia','Indonesia Kalimantan Commerce Hub'],
  ['Balikpapan','Indonesia','Indonesia Oil Commerce Hub'],
  ['Manado','Indonesia','Indonesia North Sulawesi Hub'],
  ['Padang','Indonesia','Indonesia West Sumatra Commerce Hub'],
  ['Pekanbaru','Indonesia','Indonesia Sumatra Commerce Hub'],
  ['Batam','Indonesia','Indonesia Free Trade Zone Hub'],
  ['Denpasar','Indonesia','Bali Tourism Commerce Hub'],
  ['Malang','Indonesia','East Java Education Commerce Hub'],
  ['Banjarmasin','Indonesia','Kalimantan Commerce Hub'],
  ['Bangkok','Thailand','Regional Enterprise & Trade Capital'],
  ['Chiang Mai','Thailand','North Thailand Digital Hub'],
  ['Phuket','Thailand','Thailand Tourism Commerce Hub'],
  ['Pattaya','Thailand','Thailand Eastern Seaboard Hub'],
  ['Khon Kaen','Thailand','Northeast Thailand Commerce Hub'],
  ['Hat Yai','Thailand','South Thailand Commerce Gateway'],
  ['Nakhon Ratchasima','Thailand','Thailand Northeast Commerce Hub'],
  ['Udon Thani','Thailand','Thailand Northeast Commerce Hub'],
  ['Chiang Rai','Thailand','Thailand Northern Commerce Hub'],
  ['Nonthaburi','Thailand','Bangkok Metro Commerce Hub'],
  ['Manila','Philippines','Global BPO & Staffing Capital'],
  ['Cebu','Philippines','Philippines IT & BPO Hub'],
  ['Davao','Philippines','Mindanao Commerce Capital'],
  ['Quezon City','Philippines','Metro Manila Educational Hub'],
  ['Makati','Philippines','Philippines Financial District'],
  ['Taguig','Philippines','BGC Philippines Tech Hub'],
  ['Iloilo','Philippines','Philippines Visayas Commerce Hub'],
  ['Cagayan de Oro','Philippines','Mindanao Commerce Hub'],
  ['General Santos','Philippines','Philippines Tuna Capital Hub'],
  ['Zamboanga','Philippines','Philippines Mindanao Port Hub'],
  ['Ho Chi Minh City','Vietnam','Vietnam Commercial & Tech Capital'],
  ['Hanoi','Vietnam','Vietnam Northern Enterprise Capital'],
  ['Da Nang','Vietnam','Vietnam Central Tech Hub'],
  ['Hai Phong','Vietnam','Vietnam Northern Port Hub'],
  ['Can Tho','Vietnam','Mekong Delta Commerce Hub'],
  ['Hue','Vietnam','Vietnam Heritage Commerce Hub'],
  ['Nha Trang','Vietnam','Vietnam Coastal Commerce Hub'],
  ['Vung Tau','Vietnam','Vietnam Oil Commerce Hub'],
  ['Bien Hoa','Vietnam','Vietnam Industrial Commerce Hub'],
  ['Buon Ma Thuot','Vietnam','Vietnam Central Highlands Hub'],
  ['Phnom Penh','Cambodia','Mekong Commerce Capital'],
  ['Siem Reap','Cambodia','Cambodia Tourism Commerce Hub'],
  ['Sihanoukville','Cambodia','Cambodia Port Commerce Hub'],
  ['Vientiane','Laos','Mekong Regional Capital'],
  ['Luang Prabang','Laos','Laos Heritage Tourism Hub'],
  ['Yangon','Myanmar','Myanmar Commerce & Trade Capital'],
  ['Mandalay','Myanmar','Myanmar Northern Commerce Hub'],
  ['Nay Pyi Taw','Myanmar','Myanmar Capital Commerce Hub'],
  ['Colombo','Sri Lanka','Sri Lanka Commerce Capital'],
  ['Kandy','Sri Lanka','Sri Lanka Central Heritage Hub'],
  ['Galle','Sri Lanka','Sri Lanka Southern Commerce Hub'],
  ['Jaffna','Sri Lanka','Sri Lanka Northern Commerce Hub'],
  ['Dhaka','Bangladesh','Bangladesh Commerce & Garment Capital'],
  ['Chittagong','Bangladesh','Bangladesh Port & Industrial Hub'],
  ['Sylhet','Bangladesh','Bangladesh Tea & Diaspora Hub'],
  ['Rajshahi','Bangladesh','Bangladesh Northern Commerce Hub'],
  ['Khulna','Bangladesh','Bangladesh Port Commerce Hub'],
  ['Rangpur','Bangladesh','Bangladesh Northern Commerce Hub'],
  ['Barisal','Bangladesh','Bangladesh Southern Commerce Hub'],
  ['Comilla','Bangladesh','Bangladesh Commerce Hub'],
  ['Narayanganj','Bangladesh','Bangladesh Industrial Hub'],
  ['Kathmandu','Nepal','Nepal Commerce & Tourism Capital'],
  ['Pokhara','Nepal','Nepal Tourism Commerce Hub'],
  ['Biratnagar','Nepal','Nepal Eastern Commerce Hub'],
  ['Birgunj','Nepal','Nepal Southern Commerce Hub'],
  ['Taipei','Taiwan','Taiwan Semiconductor & Innovation Hub'],
  ['Taichung','Taiwan','Taiwan Central Industrial Hub'],
  ['Kaohsiung','Taiwan','Taiwan Southern Port & Industry'],
  ['Tainan','Taiwan','Taiwan Southern Cultural Commerce Hub'],
  ['Hong Kong','Hong Kong SAR','Asia Pacific Financial Center'],
  ['Macau','Macau SAR','Asia Pacific Hospitality Hub'],

  // ─── EAST ASIA ────────────────────────────────────────────────────────────
  ['Tokyo','Japan','Japan Technology & Commerce Capital'],
  ['Osaka','Japan','Japan Western Commerce Hub'],
  ['Yokohama','Japan','Japan Port & Innovation Hub'],
  ['Nagoya','Japan','Japan Automotive Capital'],
  ['Sapporo','Japan','Hokkaido Regional Commerce Hub'],
  ['Fukuoka','Japan','Japan Western Gateway City'],
  ['Kobe','Japan','Japan Trade & Cultural Hub'],
  ['Kyoto','Japan','Japan Cultural & Tech Hub'],
  ['Sendai','Japan','Japan Tohoku Commerce Hub'],
  ['Hiroshima','Japan','Japan Western Honshu Commerce Hub'],
  ['Kawasaki','Japan','Japan Industrial Commerce Hub'],
  ['Seoul','South Korea','Korea Tech & Entertainment Capital'],
  ['Busan','South Korea','Korea Southern Port & Commerce'],
  ['Incheon','South Korea','Korea Gateway & Free Trade Zone'],
  ['Daegu','South Korea','Korea Commerce Hub'],
  ['Daejeon','South Korea','Korea Science & Research Hub'],
  ['Gwangju','South Korea','Korea Southern Cultural Hub'],
  ['Suwon','South Korea','Korea Samsung City Commerce Hub'],
  ['Ulsan','South Korea','Korea Industrial Commerce Hub'],
  ['Jeju','South Korea','Korea Island Tourism Hub'],
  ['Beijing','China','China Capital & Tech Policy Hub'],
  ['Shanghai','China','China Financial & Commerce Capital'],
  ['Guangzhou','China','China Southern Manufacturing Hub'],
  ['Shenzhen','China','China Innovation & Tech Valley'],
  ['Chengdu','China','China Western Commerce Hub'],
  ['Wuhan','China','China Central Commerce Hub'],
  ["Xi'an",'China','China Northwestern Heritage Hub'],
  ['Nanjing','China','China Eastern Tech Hub'],
  ['Hangzhou','China','China Digital Commerce Hub'],
  ['Tianjin','China','China Northern Port & Industry'],
  ['Chongqing','China','China Southwestern Commerce Megacity'],
  ['Shenyang','China','China Northeast Industrial Hub'],
  ['Zhengzhou','China','China Central Railway Hub'],
  ['Harbin','China','China Northern Heritage Hub'],
  ['Qingdao','China','China Eastern Port City'],
  ['Kunming','China','China Yunnan Commerce Hub'],
  ['Xiamen','China','China SEZ Commerce Hub'],
  ['Changsha','China','China Hunan Commerce Hub'],
  ['Hefei','China','China Anhui Commerce Hub'],
  ['Nanning','China','China Guangxi Commerce Hub'],
  ['Fuzhou','China','China Fujian Commerce Hub'],
  ['Jinan','China','China Shandong Commerce Hub'],
  ['Nanchang','China','China Jiangxi Commerce Hub'],
  ['Dalian','China','China Northern Port Commerce Hub'],
  ['Changchun','China','China Automotive Commerce Hub'],
  ['Taiyuan','China','China Shanxi Commerce Hub'],
  ['Guiyang','China','China Big Data Commerce Hub'],
  ['Urumqi','China','China Xinjiang Commerce Hub'],
  ['Ulaanbaatar','Mongolia','Mongolia Commerce Capital'],

  // ─── CENTRAL & SOUTH ASIA ────────────────────────────────────────────────
  ['Tashkent','Uzbekistan','Central Asia Commerce Capital'],
  ['Samarkand','Uzbekistan','Uzbekistan Heritage Commerce Hub'],
  ['Almaty','Kazakhstan','Kazakhstan Financial Commerce Hub'],
  ['Nur-Sultan','Kazakhstan','Kazakhstan Capital Tech Hub'],
  ['Shymkent','Kazakhstan','Kazakhstan Commerce Hub'],
  ['Baku','Azerbaijan','Caucasus Energy & Commerce Capital'],
  ['Ganja','Azerbaijan','Azerbaijan Commerce Hub'],
  ['Tbilisi','Georgia','Caucasus Commerce & Tech Hub'],
  ['Kutaisi','Georgia','Georgia Commerce Hub'],
  ['Yerevan','Armenia','Armenia Capital Commerce Hub'],
  ['Bishkek','Kyrgyzstan','Central Asia Commerce Hub'],
  ['Osh','Kyrgyzstan','Kyrgyzstan Second City Hub'],
  ['Dushanbe','Tajikistan','Central Asia Capital Hub'],
  ['Ashgabat','Turkmenistan','Turkmenistan Commerce Capital'],
  ['Mary','Turkmenistan','Turkmenistan Commerce Hub'],
  ['Kabul','Afghanistan','Afghanistan Commerce Capital'],
  ['Mazar-i-Sharif','Afghanistan','Afghanistan Northern Commerce Hub'],
  ['Herat','Afghanistan','Afghanistan Western Commerce Hub'],
  ['Kandahar','Afghanistan','Afghanistan Southern Commerce Hub'],
  ['Male','Maldives','Maldives Tourism Commerce Capital'],
  ['Thimphu','Bhutan','Bhutan Capital Commerce Hub'],

  // ─── EUROPE ───────────────────────────────────────────────────────────────
  ['London','United Kingdom','Global Business & Finance Hub'],
  ['Manchester','United Kingdom','UK Northern Powerhouse Hub'],
  ['Birmingham','United Kingdom','UK Midlands Enterprise Hub'],
  ['Glasgow','United Kingdom','Scotland Commerce & Innovation Hub'],
  ['Edinburgh','United Kingdom','Scotland Financial Hub'],
  ['Leeds','United Kingdom','UK North England Commerce Hub'],
  ['Liverpool','United Kingdom','UK Northwest Maritime Commerce Hub'],
  ['Bristol','United Kingdom','UK Southwest Tech Commerce Hub'],
  ['Sheffield','United Kingdom','UK Steel City Commerce Hub'],
  ['Newcastle UK','United Kingdom','UK Northeast Commerce Hub'],
  ['Nottingham','United Kingdom','UK Midlands Commerce Hub'],
  ['Leicester','United Kingdom','UK Midlands Commerce Hub'],
  ['Coventry','United Kingdom','UK Midlands Commerce Hub'],
  ['Bradford','United Kingdom','UK Textile Commerce Hub'],
  ['Stoke-on-Trent','United Kingdom','UK Pottery Commerce Hub'],
  ['Wolverhampton','United Kingdom','UK Midlands Commerce Hub'],
  ['Southampton','United Kingdom','UK South Coast Commerce Hub'],
  ['Cardiff','United Kingdom','Wales Commerce Capital'],
  ['Belfast','United Kingdom','Northern Ireland Commerce Hub'],
  ['Paris','France','European Fashion & Finance Capital'],
  ['Lyon','France','France Second City Commerce Hub'],
  ['Marseille','France','France Mediterranean Port Hub'],
  ['Toulouse','France','France Aerospace & Tech Hub'],
  ['Nice','France','French Riviera Commerce Hub'],
  ['Nantes','France','France Atlantic Commerce Hub'],
  ['Strasbourg','France','France EU Capital Commerce Hub'],
  ['Bordeaux','France','France Southwest Commerce Hub'],
  ['Montpellier','France','France Southern Commerce Hub'],
  ['Rennes','France','France Western Tech Hub'],
  ['Lille','France','France Northern Commerce Hub'],
  ['Grenoble','France','France Alps Innovation Hub'],
  ['Toulon','France','France Naval Commerce Hub'],
  ['Berlin','Germany','Germany Startup & Tech Capital'],
  ['Munich','Germany','Germany Automotive & Finance Hub'],
  ['Hamburg','Germany','Germany Northern Port & Commerce'],
  ['Frankfurt','Germany','Germany Financial & Banking Capital'],
  ['Cologne','Germany','Germany Western Commerce Hub'],
  ['Stuttgart','Germany','Germany Engineering Hub'],
  ['Dusseldorf','Germany','Germany Fashion Commerce Hub'],
  ['Leipzig','Germany','Germany Eastern Commerce Hub'],
  ['Dortmund','Germany','Germany Ruhr Commerce Hub'],
  ['Bremen','Germany','Germany Maritime Commerce Hub'],
  ['Nuremberg','Germany','Germany Commerce Hub'],
  ['Dresden','Germany','Germany Eastern Commerce Hub'],
  ['Hannover','Germany','Germany Fair Commerce Hub'],
  ['Bochum','Germany','Germany Ruhr Commerce Hub'],
  ['Wuppertal','Germany','Germany Commerce Hub'],
  ['Bielefeld','Germany','Germany Commerce Hub'],
  ['Mannheim','Germany','Germany Commerce Hub'],
  ['Barcelona','Spain','Spain Tech & Tourism Capital'],
  ['Madrid','Spain','Spain Enterprise & Finance Capital'],
  ['Valencia','Spain','Spain Eastern Commerce Hub'],
  ['Seville','Spain','Spain Southern Commerce Hub'],
  ['Bilbao','Spain','Spain Northern Industrial Hub'],
  ['Malaga','Spain','Spain Costa Sol Commerce Hub'],
  ['Zaragoza','Spain','Spain Northeast Commerce Hub'],
  ['Palma','Spain','Spain Balearic Commerce Hub'],
  ['Murcia','Spain','Spain Southeast Commerce Hub'],
  ['Alicante','Spain','Spain Costa Blanca Commerce Hub'],
  ['Las Palmas','Spain','Spain Canary Islands Hub'],
  ['Valladolid','Spain','Spain Commerce Hub'],
  ['Rome','Italy','Italy Capital Heritage Commerce Hub'],
  ['Milan','Italy','Italy Fashion & Finance Capital'],
  ['Naples','Italy','Italy Southern Commerce Hub'],
  ['Turin','Italy','Italy Automotive & Innovation Hub'],
  ['Palermo','Italy','Sicily Commerce Hub'],
  ['Genoa','Italy','Italy Port Commerce Hub'],
  ['Bologna','Italy','Italy Commerce Hub'],
  ['Florence','Italy','Italy Art & Commerce Hub'],
  ['Bari','Italy','Italy Southern Commerce Hub'],
  ['Catania','Italy','Italy Sicily Commerce Hub'],
  ['Verona','Italy','Italy Commerce & Fair Hub'],
  ['Venice','Italy','Italy Tourism Commerce Hub'],
  ['Messina','Italy','Italy Sicily Commerce Hub'],
  ['Amsterdam','Netherlands','European Tech & Logistics Hub'],
  ['Rotterdam','Netherlands','Europe Port Commerce Capital'],
  ['The Hague','Netherlands','Netherlands Legal Commerce Hub'],
  ['Utrecht','Netherlands','Netherlands Commerce Hub'],
  ['Eindhoven','Netherlands','Netherlands Tech Commerce Hub'],
  ['Tilburg','Netherlands','Netherlands Commerce Hub'],
  ['Brussels','Belgium','EU Capital & Governance Hub'],
  ['Antwerp','Belgium','Belgium Port & Diamond Commerce'],
  ['Ghent','Belgium','Belgium Commerce Hub'],
  ['Vienna','Austria','Central Europe Commerce Capital'],
  ['Graz','Austria','Austria Commerce Hub'],
  ['Linz','Austria','Austria Commerce Hub'],
  ['Zurich','Switzerland','Global Finance & Banking Capital'],
  ['Geneva','Switzerland','Switzerland International Commerce Hub'],
  ['Bern','Switzerland','Switzerland Capital Commerce Hub'],
  ['Basel','Switzerland','Switzerland Pharma Commerce Hub'],
  ['Lausanne','Switzerland','Switzerland Commerce Hub'],
  ['Stockholm','Sweden','Nordic Tech & Innovation Capital'],
  ['Gothenburg','Sweden','Sweden Maritime Commerce Hub'],
  ['Malmo','Sweden','Sweden Southern Commerce Hub'],
  ['Uppsala','Sweden','Sweden Academic Commerce Hub'],
  ['Oslo','Norway','Norwegian Energy Commerce Capital'],
  ['Bergen','Norway','Norway Maritime Commerce Hub'],
  ['Trondheim','Norway','Norway Commerce Hub'],
  ['Copenhagen','Denmark','Nordic Design & Commerce Capital'],
  ['Aarhus','Denmark','Denmark Second City Hub'],
  ['Odense','Denmark','Denmark Commerce Hub'],
  ['Helsinki','Finland','Nordic Digital Commerce Capital'],
  ['Tampere','Finland','Finland Industrial Commerce Hub'],
  ['Oulu','Finland','Finland Northern Commerce Hub'],
  ['Dublin','Ireland','European Tech MNC Capital'],
  ['Cork','Ireland','Ireland Southern Commerce Hub'],
  ['Lisbon','Portugal','Iberian Tech & Tourism Capital'],
  ['Porto','Portugal','Portugal Northern Commerce Hub'],
  ['Athens','Greece','Greek Heritage Commerce Capital'],
  ['Thessaloniki','Greece','Greece Northern Commerce Hub'],
  ['Patras','Greece','Greece Port Commerce Hub'],
  ['Warsaw','Poland','Polish Commerce & Tech Capital'],
  ['Krakow','Poland','Poland Cultural Commerce Hub'],
  ['Lodz','Poland','Poland Textile Commerce Hub'],
  ['Wroclaw','Poland','Poland Western Commerce Hub'],
  ['Poznan','Poland','Poland Commerce Hub'],
  ['Gdansk','Poland','Poland Baltic Port Commerce Hub'],
  ['Prague','Czech Republic','Central Europe Heritage & Tech Hub'],
  ['Brno','Czech Republic','Czech Tech Commerce Hub'],
  ['Budapest','Hungary','Central Europe Finance Commerce Hub'],
  ['Debrecen','Hungary','Hungary Commerce Hub'],
  ['Bucharest','Romania','Eastern Europe Commerce Capital'],
  ['Cluj-Napoca','Romania','Romania Tech Commerce Hub'],
  ['Timisoara','Romania','Romania Western Commerce Hub'],
  ['Iasi','Romania','Romania Eastern Commerce Hub'],
  ['Sofia','Bulgaria','Bulgaria Commerce Capital'],
  ['Plovdiv','Bulgaria','Bulgaria Commerce Hub'],
  ['Belgrade','Serbia','Balkans Commerce Capital'],
  ['Novi Sad','Serbia','Serbia Commerce Hub'],
  ['Zagreb','Croatia','Croatia Commerce Capital'],
  ['Split','Croatia','Croatia Tourism Commerce Hub'],
  ['Sarajevo','Bosnia','Balkans Commerce Hub'],
  ['Ljubljana','Slovenia','Slovenia Commerce Hub'],
  ['Skopje','North Macedonia','Balkans Commerce Hub'],
  ['Tirana','Albania','Albania Commerce Capital'],
  ['Podgorica','Montenegro','Montenegro Commerce Hub'],
  ['Chisinau','Moldova','Moldova Commerce Capital'],
  ['Kyiv','Ukraine','Eastern Europe Tech Commerce Capital'],
  ['Kharkiv','Ukraine','Ukraine Eastern Commerce Hub'],
  ['Lviv','Ukraine','Ukraine Western Commerce Hub'],
  ['Odessa','Ukraine','Ukraine Port Commerce Hub'],
  ['Dnipro','Ukraine','Ukraine Commerce Hub'],
  ['Minsk','Belarus','Belarus Commerce Capital'],
  ['Vilnius','Lithuania','Baltic Commerce Capital'],
  ['Riga','Latvia','Baltic Commerce Hub'],
  ['Tallinn','Estonia','Baltic Digital Commerce Hub'],
  ['Helsinki','Finland','Nordic Digital Commerce Capital'],
  ['Reykjavik','Iceland','Nordic Island Commerce Hub'],
  ['Valletta','Malta','Malta Mediterranean Commerce Hub'],
  ['Nicosia','Cyprus','Cyprus Commerce Capital'],
  ['Luxembourg City','Luxembourg','EU Finance Commerce Capital'],
  ['Moscow','Russia','Russia Commerce & Enterprise Capital'],
  ['Saint Petersburg','Russia','Russia Cultural Commerce Hub'],
  ['Novosibirsk','Russia','Russia Siberian Commerce Hub'],
  ['Yekaterinburg','Russia','Russia Urals Commerce Hub'],
  ['Nizhny Novgorod','Russia','Russia Commerce Hub'],
  ['Kazan','Russia','Russia Tatarstan Commerce Hub'],
  ['Samara','Russia','Russia Commerce Hub'],
  ['Rostov-on-Don','Russia','Russia Southern Commerce Hub'],
  ['Ufa','Russia','Russia Bashkortostan Commerce Hub'],
  ['Omsk','Russia','Russia Siberia Commerce Hub'],
  ['Chelyabinsk','Russia','Russia Commerce Hub'],
  ['Krasnoyarsk','Russia','Russia Siberia Commerce Hub'],
  ['Vladivostok','Russia','Russia Pacific Gateway Hub'],

  // ─── AFRICA ───────────────────────────────────────────────────────────────
  ['Lagos','Nigeria','West Africa Commerce & Tech Capital'],
  ['Abuja','Nigeria','Nigeria Capital Commerce Hub'],
  ['Port Harcourt','Nigeria','Nigeria Oil & Industrial Hub'],
  ['Kano','Nigeria','Nigeria Northern Commerce Hub'],
  ['Ibadan','Nigeria','Nigeria Southwest Commerce Hub'],
  ['Kaduna','Nigeria','Nigeria North Central Hub'],
  ['Enugu','Nigeria','Nigeria Southeast Commerce Hub'],
  ['Benin City','Nigeria','Nigeria South-South Commerce Hub'],
  ['Onitsha','Nigeria','Nigeria Biggest Market Hub'],
  ['Calabar','Nigeria','Nigeria Tourism Commerce Hub'],
  ['Warri','Nigeria','Nigeria Oil Delta Commerce Hub'],
  ['Aba','Nigeria','Nigeria Southeast Commerce Hub'],
  ['Jos','Nigeria','Nigeria Plateau Commerce Hub'],
  ['Ilorin','Nigeria','Nigeria North Central Commerce Hub'],
  ['Maiduguri','Nigeria','Nigeria Northeast Commerce Hub'],
  ['Nairobi','Kenya','East Africa Tech & Commerce Capital'],
  ['Mombasa','Kenya','Kenya Coastal Commerce Hub'],
  ['Kisumu','Kenya','Kenya Lake Commerce Hub'],
  ['Nakuru','Kenya','Kenya Rift Valley Commerce Hub'],
  ['Eldoret','Kenya','Kenya Commerce Hub'],
  ['Thika','Kenya','Kenya Industrial Commerce Hub'],
  ['Johannesburg','South Africa','Africa Financial Commerce Capital'],
  ['Cape Town','South Africa','South Africa Tourism & Tech Hub'],
  ['Durban','South Africa','South Africa Port Commerce Hub'],
  ['Pretoria','South Africa','South Africa Capital Hub'],
  ['Port Elizabeth','South Africa','South Africa Eastern Port Hub'],
  ['Bloemfontein','South Africa','South Africa Central Commerce Hub'],
  ['East London SA','South Africa','South Africa Eastern Commerce Hub'],
  ['Polokwane','South Africa','South Africa Northern Commerce Hub'],
  ['Nelspruit','South Africa','South Africa Eastern Commerce Hub'],
  ['Accra','Ghana','West Africa Digital Commerce Hub'],
  ['Kumasi','Ghana','Ghana Ashanti Commerce Hub'],
  ['Tamale','Ghana','Ghana Northern Commerce Hub'],
  ['Sekondi-Takoradi','Ghana','Ghana Port Commerce Hub'],
  ['Addis Ababa','Ethiopia','East Africa Commerce Capital'],
  ['Dire Dawa','Ethiopia','Ethiopia Commerce Hub'],
  ['Bahir Dar','Ethiopia','Ethiopia Lake Commerce Hub'],
  ['Mekelle','Ethiopia','Ethiopia Northern Commerce Hub'],
  ['Hawassa','Ethiopia','Ethiopia Southern Commerce Hub'],
  ['Dar es Salaam','Tanzania','East Africa Port Commerce Capital'],
  ['Dodoma','Tanzania','Tanzania Capital Hub'],
  ['Mwanza','Tanzania','Tanzania Lake Commerce Hub'],
  ['Arusha','Tanzania','Tanzania Tourism Commerce Hub'],
  ['Kampala','Uganda','East Africa Startup Commerce Hub'],
  ['Gulu','Uganda','Uganda Northern Commerce Hub'],
  ['Entebbe','Uganda','Uganda Commerce Hub'],
  ['Mbarara','Uganda','Uganda Southwest Commerce Hub'],
  ['Kigali','Rwanda','Africa Innovation Commerce Capital'],
  ['Lusaka','Zambia','Zambia Commerce Capital'],
  ['Ndola','Zambia','Zambia Commerce Hub'],
  ['Kitwe','Zambia','Zambia Copper Belt Hub'],
  ['Harare','Zimbabwe','Zimbabwe Commerce Capital'],
  ['Bulawayo','Zimbabwe','Zimbabwe Second Commerce Hub'],
  ['Maputo','Mozambique','Mozambique Port Commerce Hub'],
  ['Beira','Mozambique','Mozambique Commerce Hub'],
  ['Luanda','Angola','Angola Commerce Capital'],
  ['Huambo','Angola','Angola Commerce Hub'],
  ['Lobito','Angola','Angola Port Commerce Hub'],
  ['Dakar','Senegal','West Africa Atlantic Commerce Hub'],
  ['Abidjan',"Côte d'Ivoire",'West Africa Commerce Capital'],
  ['Douala','Cameroon','Central Africa Commerce Port'],
  ['Yaounde','Cameroon','Cameroon Capital Commerce Hub'],
  ['Kinshasa','DR Congo','Central Africa Commerce Capital'],
  ['Lubumbashi','DR Congo','DRC Mining Commerce Hub'],
  ['Antananarivo','Madagascar','Madagascar Commerce Capital'],
  ['Port Louis','Mauritius','Mauritius Commerce & Finance Hub'],
  ['Windhoek','Namibia','Namibia Commerce Capital'],
  ['Gaborone','Botswana','Botswana Commerce Capital'],
  ['Lilongwe','Malawi','Malawi Commerce Capital'],
  ['Blantyre','Malawi','Malawi Commerce Hub'],
  ['Khartoum','Sudan','Sudan Commerce Capital'],
  ['Juba','South Sudan','South Sudan Commerce Capital'],
  ['Mogadishu','Somalia','Somalia Commerce Capital'],
  ['Hargeisa','Somaliland','Somaliland Commerce Capital'],
  ['Djibouti City','Djibouti','Horn of Africa Port Hub'],
  ['Asmara','Eritrea','Eritrea Commerce Capital'],
  ['Bamako','Mali','Mali Commerce Capital'],
  ['Ouagadougou','Burkina Faso','Burkina Faso Commerce Capital'],
  ['Niamey','Niger','Niger Commerce Capital'],
  ['Conakry','Guinea','Guinea Commerce Capital'],
  ['Freetown','Sierra Leone','Sierra Leone Commerce Capital'],
  ['Monrovia','Liberia','Liberia Commerce Capital'],
  ['Lome','Togo','West Africa Port Commerce Hub'],
  ['Cotonou','Benin','Benin Port Commerce Hub'],
  ['Abuja FCT','Nigeria','Nigeria FCT Commerce Zone'],
  ['Ndjamena','Chad','Chad Commerce Capital'],
  ['Bangui','Central African Republic','CAR Commerce Capital'],
  ['Libreville','Gabon','Gabon Commerce Capital'],
  ['Brazzaville','Congo','Congo Commerce Capital'],
  ['Pointe-Noire','Congo','Congo Port Commerce Hub'],

  // ─── LATIN AMERICA ────────────────────────────────────────────────────────
  ['São Paulo','Brazil','Latin America Financial Commerce Capital'],
  ['Rio de Janeiro','Brazil','Brazil Tourism & Commerce Hub'],
  ['Brasilia','Brazil','Brazil Capital Government Hub'],
  ['Belo Horizonte','Brazil','Brazil Southeastern Commerce Hub'],
  ['Fortaleza','Brazil','Brazil Northeast Commerce Capital'],
  ['Salvador','Brazil','Brazil Northeast Cultural Hub'],
  ['Curitiba','Brazil','Brazil Southern Commerce Hub'],
  ['Manaus','Brazil','Brazil Amazon Commerce Hub'],
  ['Recife','Brazil','Brazil Northeast Tech Commerce Hub'],
  ['Porto Alegre','Brazil','Brazil Southernmost Commerce Hub'],
  ['Belem','Brazil','Brazil Amazon Gateway Hub'],
  ['Goiania','Brazil','Brazil Central Commerce Hub'],
  ['Campinas','Brazil','Brazil Technology Commerce Hub'],
  ['Sao Luis','Brazil','Brazil Maranhao Commerce Hub'],
  ['Maceio','Brazil','Brazil Alagoas Commerce Hub'],
  ['Natal','Brazil','Brazil Rio Grande do Norte Hub'],
  ['Teresina','Brazil','Brazil Piaui Commerce Hub'],
  ['Cuiaba','Brazil','Brazil Central West Commerce Hub'],
  ['Campo Grande','Brazil','Brazil Mato Grosso do Sul Hub'],
  ['Florianopolis','Brazil','Brazil South Commerce Hub'],
  ['Joao Pessoa','Brazil','Brazil Northeast Commerce Hub'],
  ['Aracaju','Brazil','Brazil Sergipe Commerce Hub'],
  ['Porto Velho','Brazil','Brazil Rondonia Commerce Hub'],
  ['Vitoria','Brazil','Brazil Espirito Santo Commerce Hub'],
  ['Mexico City','Mexico','Latin America Mega Commerce Capital'],
  ['Guadalajara','Mexico','Mexico Tech Silicon Valley'],
  ['Monterrey','Mexico','Mexico Industrial Commerce Hub'],
  ['Puebla','Mexico','Mexico Central Commerce Hub'],
  ['Tijuana','Mexico','Mexico Border Commerce Hub'],
  ['Leon','Mexico','Mexico Leather Commerce Hub'],
  ['Juarez','Mexico','Mexico Border Industrial Hub'],
  ['Merida MX','Mexico','Mexico Yucatan Commerce Hub'],
  ['Cancun','Mexico','Mexico Caribbean Tourism Hub'],
  ['Queretaro','Mexico','Mexico Industrial Commerce Hub'],
  ['Toluca','Mexico','Mexico State Capital Commerce Hub'],
  ['San Luis Potosi','Mexico','Mexico Commerce Hub'],
  ['Aguascalientes','Mexico','Mexico Commerce Hub'],
  ['Hermosillo','Mexico','Mexico Sonora Commerce Hub'],
  ['Chihuahua','Mexico','Mexico Northern Commerce Hub'],
  ['Saltillo','Mexico','Mexico Commerce Hub'],
  ['Morelia','Mexico','Mexico Michoacan Commerce Hub'],
  ['Veracruz','Mexico','Mexico Gulf Port Commerce Hub'],
  ['Bogota','Colombia','Colombia Commerce & Tech Capital'],
  ['Medellin','Colombia','Colombia Innovation Commerce Hub'],
  ['Cali','Colombia','Colombia Southwest Commerce Hub'],
  ['Barranquilla','Colombia','Colombia Caribbean Commerce Hub'],
  ['Cartagena','Colombia','Colombia Port Commerce Hub'],
  ['Bucaramanga','Colombia','Colombia Commerce Hub'],
  ['Cucuta','Colombia','Colombia Border Commerce Hub'],
  ['Pereira','Colombia','Colombia Coffee Region Hub'],
  ['Manizales','Colombia','Colombia Coffee Commerce Hub'],
  ['Ibague','Colombia','Colombia Commerce Hub'],
  ['Lima','Peru','Peru Commerce & Finance Capital'],
  ['Arequipa','Peru','Peru Southern Commerce Hub'],
  ['Trujillo','Peru','Peru Northern Commerce Hub'],
  ['Chiclayo','Peru','Peru Commerce Hub'],
  ['Piura','Peru','Peru Northwest Commerce Hub'],
  ['Iquitos','Peru','Peru Amazon Commerce Hub'],
  ['Santiago','Chile','Chile Commerce & Finance Capital'],
  ['Valparaiso','Chile','Chile Port Commerce Hub'],
  ['Concepcion','Chile','Chile Southern Commerce Hub'],
  ['Antofagasta','Chile','Chile Mining Commerce Hub'],
  ['Iquique','Chile','Chile Northern Commerce Hub'],
  ['Buenos Aires','Argentina','Argentina Commerce & Finance Capital'],
  ['Cordoba','Argentina','Argentina Commerce Hub'],
  ['Rosario','Argentina','Argentina Commerce Hub'],
  ['Mendoza','Argentina','Argentina Wine Commerce Hub'],
  ['Tucuman','Argentina','Argentina Northwest Commerce Hub'],
  ['La Plata','Argentina','Argentina Commerce Hub'],
  ['Mar del Plata','Argentina','Argentina Coast Commerce Hub'],
  ['Caracas','Venezuela','Venezuela Commerce Capital'],
  ['Maracaibo','Venezuela','Venezuela Oil Commerce Hub'],
  ['Valencia VZ','Venezuela','Venezuela Commerce Hub'],
  ['Barquisimeto','Venezuela','Venezuela Commerce Hub'],
  ['Quito','Ecuador','Ecuador Commerce Capital'],
  ['Guayaquil','Ecuador','Ecuador Port Commerce Hub'],
  ['Cuenca EC','Ecuador','Ecuador Commerce Hub'],
  ['La Paz','Bolivia','Bolivia Commerce & Governance Hub'],
  ['Santa Cruz BO','Bolivia','Bolivia Eastern Commerce Hub'],
  ['Cochabamba','Bolivia','Bolivia Commerce Hub'],
  ['Asuncion','Paraguay','Paraguay Commerce Capital'],
  ['Ciudad del Este','Paraguay','Paraguay Commerce Hub'],
  ['Montevideo','Uruguay','Uruguay Commerce Capital'],
  ['Panama City','Panama','Central America Logistics Hub'],
  ['Colon','Panama','Panama Free Trade Zone Hub'],
  ['San Jose CR','Costa Rica','Central America Tech Commerce Hub'],
  ['Guatemala City','Guatemala','Central America Commerce Capital'],
  ['Tegucigalpa','Honduras','Honduras Commerce Capital'],
  ['San Pedro Sula','Honduras','Honduras Commerce Hub'],
  ['San Salvador','El Salvador','El Salvador Commerce Capital'],
  ['Managua','Nicaragua','Nicaragua Commerce Capital'],
  ['Havana','Cuba','Caribbean Commerce Hub'],
  ['Santo Domingo','Dominican Republic','Caribbean Commerce Capital'],
  ['Kingston','Jamaica','Caribbean Island Commerce Hub'],
  ['Port of Spain','Trinidad and Tobago','Caribbean Commerce Hub'],
  ['Bridgetown','Barbados','Caribbean Commerce Hub'],

  // ─── NORTH AMERICA ────────────────────────────────────────────────────────
  ['New York','USA (NY)','Global Financial & Media Capital'],
  ['San Francisco','USA (CA)','Silicon Valley Innovation Hub'],
  ['Los Angeles','USA (CA)','Media, Trade & Enterprise Hub'],
  ['Chicago','USA (IL)','Midwest Commercial Capital'],
  ['Houston','USA (TX)','Energy & Diverse Enterprise Hub'],
  ['Dallas','USA (TX)','Southwest Corporate HQ Hub'],
  ['Austin','USA (TX)','Enterprise Tech & Startup Hub'],
  ['Seattle','USA (WA)','Cloud & Enterprise SaaS Hub'],
  ['Boston','USA (MA)','Healthcare & Biotech Innovation Hub'],
  ['Atlanta','USA (GA)','Southeast US Enterprise Hub'],
  ['Miami','USA (FL)','Latin America Gateway & Fintech Hub'],
  ['Phoenix','USA (AZ)','Southwest Growth & Tech Hub'],
  ['Washington DC','USA (DC)','Government & Policy Tech Hub'],
  ['Denver','USA (CO)','Mountain West Enterprise Hub'],
  ['Minneapolis','USA (MN)','Midwest Healthcare & Retail Hub'],
  ['San Diego','USA (CA)','US Defense & Biotech Coast Hub'],
  ['Portland','USA (OR)','US Pacific Northwest Commerce Hub'],
  ['Las Vegas','USA (NV)','US Entertainment & Convention Hub'],
  ['Nashville','USA (TN)','US Healthcare & Music Commerce Hub'],
  ['Charlotte','USA (NC)','US Southeast Finance Commerce Hub'],
  ['Detroit','USA (MI)','US Automotive Commerce Capital'],
  ['Philadelphia','USA (PA)','US East Coast Commerce Hub'],
  ['Columbus','USA (OH)','US Midwest Commerce Hub'],
  ['Indianapolis','USA (IN)','US Midwest Enterprise Hub'],
  ['Jacksonville','USA (FL)','US Florida Commerce Hub'],
  ['San Jose CA','USA (CA)','Silicon Valley Commerce City'],
  ['Fort Worth','USA (TX)','US Texas Commerce Hub'],
  ['Baltimore','USA (MD)','US Mid-Atlantic Commerce Hub'],
  ['Sacramento','USA (CA)','California State Capital Commerce Hub'],
  ['Oklahoma City','USA (OK)','US Great Plains Commerce Hub'],
  ['Salt Lake City','USA (UT)','US Mountain Tech Commerce Hub'],
  ['Kansas City','USA (MO)','US Heartland Commerce Hub'],
  ['Raleigh','USA (NC)','US Research Triangle Tech Hub'],
  ['Tampa','USA (FL)','Florida Gulf Coast Commerce Hub'],
  ['Orlando','USA (FL)','Florida Tourism & Tech Hub'],
  ['Pittsburgh','USA (PA)','Pennsylvania Tech Commerce Hub'],
  ['Cleveland','USA (OH)','Ohio Commerce & Healthcare Hub'],
  ['Cincinnati','USA (OH)','Ohio Commerce Hub'],
  ['St. Louis','USA (MO)','Missouri Commerce Hub'],
  ['New Orleans','USA (LA)','Louisiana Culture Commerce Hub'],
  ['San Antonio','USA (TX)','Texas Commerce Hub'],
  ['Memphis','USA (TN)','US Logistics Commerce Hub'],
  ['Louisville','USA (KY)','US Distribution Commerce Hub'],
  ['Richmond','USA (VA)','US Southeast Capital Commerce Hub'],
  ['Virginia Beach','USA (VA)','Virginia Coastal Commerce Hub'],
  ['Milwaukee','USA (WI)','Wisconsin Commerce Hub'],
  ['Omaha','USA (NE)','Nebraska Commerce Hub'],
  ['Tucson','USA (AZ)','Arizona Southern Commerce Hub'],
  ['El Paso','USA (TX)','Texas Border Commerce Hub'],
  ['Fresno','USA (CA)','California Central Valley Commerce Hub'],
  ['Mesa','USA (AZ)','Arizona Metropolitan Commerce Hub'],
  ['Fort Lauderdale','USA (FL)','Florida South Commerce Hub'],
  ['Albuquerque','USA (NM)','New Mexico Commerce Hub'],
  ['Tulsa','USA (OK)','Oklahoma Commerce Hub'],
  ['Boise','USA (ID)','Idaho Commerce Hub'],
  ['Spokane','USA (WA)','Washington State Commerce Hub'],
  ['Tacoma','USA (WA)','Washington Port Commerce Hub'],
  ['Madison','USA (WI)','Wisconsin Commerce Hub'],
  ['Grand Rapids','USA (MI)','Michigan Commerce Hub'],
  ['Wichita','USA (KS)','Kansas Commerce Hub'],
  ['Des Moines','USA (IA)','Iowa Commerce Hub'],
  ['Birmingham AL','USA (AL)','Alabama Commerce Hub'],
  ['Greensboro','USA (NC)','North Carolina Commerce Hub'],
  ['Durham','USA (NC)','North Carolina Research Hub'],
  ['Columbia SC','USA (SC)','South Carolina Commerce Hub'],
  ['Charleston SC','USA (SC)','South Carolina Port Commerce Hub'],
  ['Savannah','USA (GA)','Georgia Port Commerce Hub'],
  ['Knoxville','USA (TN)','Tennessee Commerce Hub'],
  ['Providence','USA (RI)','Rhode Island Commerce Hub'],
  ['Hartford','USA (CT)','Connecticut Commerce Hub'],
  ['Buffalo','USA (NY)','New York State Northern Commerce Hub'],
  ['Rochester NY','USA (NY)','New York State Commerce Hub'],
  ['Honolulu','USA (HI)','Hawaii Pacific Commerce Hub'],
  ['Anchorage','USA (AK)','Alaska Commerce Hub'],
  ['Toronto','Canada (ON)','North America Finance & Tech Capital'],
  ['Vancouver','Canada (BC)','Pacific Gateway & Digital Hub'],
  ['Montreal','Canada (QC)','Canadian AI & Creative Hub'],
  ['Calgary','Canada (AB)','Canadian Energy & Enterprise Hub'],
  ['Ottawa','Canada (ON)','Canadian Government & Tech Capital'],
  ['Edmonton','Canada (AB)','Canada Northern Commerce Hub'],
  ['Winnipeg','Canada (MB)','Canada Prairie Commerce Hub'],
  ['Quebec City','Canada (QC)','Canada French Heritage Commerce Hub'],
  ['Mississauga','Canada (ON)','Canada Greater Toronto Hub'],
  ['Brampton','Canada (ON)','Canada South Asian Commerce Hub'],
  ['Surrey BC','Canada (BC)','Canada BC South Asian Commerce Hub'],
  ['Burnaby','Canada (BC)','Canada BC Commerce Hub'],
  ['Markham','Canada (ON)','Canada Ontario Tech Commerce Hub'],
  ['Vaughan','Canada (ON)','Canada Ontario Commerce Hub'],
  ['Halifax','Canada (NS)','Canada Atlantic Commerce Hub'],
  ['Hamilton ON','Canada (ON)','Canada Steel Commerce Hub'],
  ['Kitchener','Canada (ON)','Canada Waterloo Tech Hub'],
  ['London ON','Canada (ON)','Canada Ontario Commerce City'],
  ['Windsor ON','Canada (ON)','Canada Border Commerce Hub'],
  ['Saskatoon','Canada (SK)','Canada Prairie Commerce Hub'],
  ['Regina','Canada (SK)','Canada Saskatchewan Commerce Hub'],
  ['Victoria BC','Canada (BC)','Canada BC Capital Commerce Hub'],

  // ─── AUSTRALIA & PACIFIC ──────────────────────────────────────────────────
  ['Sydney','Australia','Australia Commerce & Finance Capital'],
  ['Melbourne','Australia','Australia Innovation & Education Hub'],
  ['Brisbane','Australia','Australia Queensland Commerce Hub'],
  ['Perth','Australia','Australia Western Mining Commerce Hub'],
  ['Adelaide','Australia','Australia South Commerce Hub'],
  ['Gold Coast','Australia','Australia Tourism Commerce Hub'],
  ['Canberra','Australia','Australia Capital Government Hub'],
  ['Newcastle AU','Australia','Australia Hunter Valley Commerce Hub'],
  ['Wollongong','Australia','Australia NSW Commerce Hub'],
  ['Hobart','Australia','Tasmania Capital Commerce Hub'],
  ['Darwin','Australia','Australia Northern Territory Hub'],
  ['Townsville','Australia','Australia North Queensland Hub'],
  ['Cairns','Australia','Australia Tropical Commerce Hub'],
  ['Auckland','New Zealand','NZ Commerce & Finance Capital'],
  ['Wellington','New Zealand','NZ Capital Government Commerce Hub'],
  ['Christchurch','New Zealand','NZ South Island Commerce Hub'],
  ['Hamilton NZ','New Zealand','NZ Waikato Commerce Hub'],
  ['Tauranga','New Zealand','NZ Bay of Plenty Commerce Hub'],
  ['Suva','Fiji','Pacific Island Commerce Capital'],
  ['Port Moresby','Papua New Guinea','Pacific Commerce Capital'],

  // ─── INDIA: MAHARASHTRA ───────────────────────────────────────────────────
  ['Mumbai','Maharashtra','India Financial Capital'],
  ['Pune','Maharashtra','Maharashtra IT & Manufacturing Hub'],
  ['Nagpur','Maharashtra','Central India Logistics Nexus'],
  ['Nashik','Maharashtra','Grape Capital & Engineering Hub'],
  ['Thane','Maharashtra','MMR Business District'],
  ['Navi Mumbai','Maharashtra','Infotech & Port Hub'],
  ['Aurangabad MH','Maharashtra','Marathwada Industrial Hub'],
  ['Solapur','Maharashtra','Textile & Commerce District'],
  ['Kolhapur','Maharashtra','Southern Maharashtra Trade Hub'],
  ['Amravati','Maharashtra','Vidarbha Commerce Center'],
  ['Nanded','Maharashtra','Marathwada Regional Hub'],
  ['Sangli','Maharashtra','Turmeric & Trade Center'],
  ['Latur','Maharashtra','Marathwada Pulse Capital'],
  ['Dhule','Maharashtra','North Maharashtra Commerce Hub'],
  ['Ahmednagar','Maharashtra','Deccan Commerce Hub'],
  ['Jalgaon','Maharashtra','Banana & Industrial Belt'],
  ['Chandrapur','Maharashtra','Vidarbha Mining Hub'],
  ['Malegaon','Maharashtra','Power Loom Commerce Hub'],
  ['Akola','Maharashtra','Vidarbha Cotton Belt'],
  ['Pimpri-Chinchwad','Maharashtra','Pune Metro Industrial Zone'],
  ['Ratnagiri','Maharashtra','Konkan Coast Commerce Hub'],
  ['Sindhudurg','Maharashtra','Maharashtra Coastal Tourism Hub'],
  ['Palghar','Maharashtra','Mumbai Metropolitan Fringe Hub'],
  ['Beed','Maharashtra','Marathwada Commerce Hub'],
  ['Yavatmal','Maharashtra','Vidarbha Agricultural Hub'],
  ['Wardha','Maharashtra','Vidarbha Gandhi Heritage Hub'],
  ['Buldhana','Maharashtra','Vidarbha Commerce District'],
  ['Washim','Maharashtra','Vidarbha Commerce Town'],
  ['Gondia','Maharashtra','East Vidarbha Rice Bowl Hub'],
  ['Bhandara','Maharashtra','Vidarbha Commerce District'],
  ['Gadchiroli','Maharashtra','East Vidarbha Forest Commerce Hub'],
  ['Osmanabad','Maharashtra','Marathwada Commerce Hub'],
  ['Hingoli','Maharashtra','Marathwada Small Industry Hub'],
  ['Parbhani','Maharashtra','Marathwada Commerce Hub'],
  ['Jalna','Maharashtra','Marathwada Commerce Hub'],
  ['Satara','Maharashtra','Western Maharashtra Commerce Hub'],
  ['Raigad','Maharashtra','Coastal Maharashtra Commerce Hub'],

  // ─── INDIA: UTTAR PRADESH ─────────────────────────────────────────────────
  ['Lucknow','Uttar Pradesh','UP Capital Commerce Hub'],
  ['Noida','Uttar Pradesh','NCR IT & Media Hub'],
  ['Kanpur','Uttar Pradesh','Leather & Industrial Hub'],
  ['Agra','Uttar Pradesh','Tourism & Commerce Hub'],
  ['Varanasi','Uttar Pradesh','Cultural & Textile Center'],
  ['Meerut','Uttar Pradesh','NCR Industrial Corridor'],
  ['Prayagraj','Uttar Pradesh','Sangam City & Education Hub'],
  ['Ghaziabad','Uttar Pradesh','NCR Industrial Gateway'],
  ['Bareilly','Uttar Pradesh','North UP Commerce Hub'],
  ['Aligarh','Uttar Pradesh','Lock & Brass Industrial City'],
  ['Moradabad','Uttar Pradesh','Brass & Handicraft Export Hub'],
  ['Saharanpur','Uttar Pradesh','Wood Craft Commerce Hub'],
  ['Gorakhpur','Uttar Pradesh','Eastern UP Trade Center'],
  ['Firozabad','Uttar Pradesh','Glass & Bangle Industry Hub'],
  ['Jhansi','Uttar Pradesh','Bundelkhand Commerce Center'],
  ['Muzaffarnagar','Uttar Pradesh','Sugar Commerce Belt'],
  ['Mathura','Uttar Pradesh','Religious & Petrochemical Hub'],
  ['Hapur','Uttar Pradesh','NCR Light Industry Hub'],
  ['Rampur','Uttar Pradesh','UP Northern Commerce Hub'],
  ['Shahjahanpur','Uttar Pradesh','UP Central Commerce Hub'],
  ['Farrukhabad','Uttar Pradesh','UP Ganges Commerce Hub'],
  ['Etawah','Uttar Pradesh','UP Western Commerce Hub'],
  ['Mirzapur','Uttar Pradesh','UP Eastern Commerce Hub'],
  ['Bulandshahr','Uttar Pradesh','NCR Peripheral Commerce Hub'],
  ['Sultanpur','Uttar Pradesh','UP Awadh Commerce Hub'],
  ['Fatehpur UP','Uttar Pradesh','UP Central Commerce Hub'],
  ['Sitapur','Uttar Pradesh','UP Tarai Commerce Hub'],
  ['Unnao','Uttar Pradesh','UP Leather Hub'],
  ['Bahraich','Uttar Pradesh','UP Nepal Border Commerce Hub'],
  ['Ballia','Uttar Pradesh','UP Eastern Commerce Hub'],
  ['Hardoi','Uttar Pradesh','UP Commerce Hub'],
  ['Etah','Uttar Pradesh','UP Commerce Hub'],
  ['Azamgarh','Uttar Pradesh','UP Eastern Commerce Hub'],
  ['Mau','Uttar Pradesh','UP Commerce Hub'],
  ['Basti','Uttar Pradesh','UP Commerce Hub'],
  ['Deoria','Uttar Pradesh','UP Eastern Commerce Hub'],
  ['Gonda','Uttar Pradesh','UP Commerce Hub'],
  ['Mainpuri','Uttar Pradesh','UP Commerce Hub'],
  ['Bijnor','Uttar Pradesh','UP Northern Commerce Hub'],
  ['Amroha','Uttar Pradesh','UP Commerce Hub'],

  // ─── INDIA: RAJASTHAN ─────────────────────────────────────────────────────
  ['Jaipur','Rajasthan','Pink City Northern Commerce Hub'],
  ['Jodhpur','Rajasthan','Handicraft & Export Center'],
  ['Udaipur','Rajasthan','Lake City Tourism & Marble Hub'],
  ['Kota','Rajasthan','Education & Industrial Hub'],
  ['Ajmer','Rajasthan','Central Rajasthan Commerce Hub'],
  ['Bikaner','Rajasthan','Desert Commerce & Food Hub'],
  ['Alwar','Rajasthan','NCR Industrial Corridor Hub'],
  ['Bhilwara','Rajasthan','Textile Capital of Rajasthan'],
  ['Sikar','Rajasthan','Shekhawati Commerce Hub'],
  ['Sri Ganganagar','Rajasthan','Northwest Agricultural Hub'],
  ['Bharatpur','Rajasthan','Eastern Rajasthan Trade Hub'],
  ['Pali','Rajasthan','Textile Processing Hub'],
  ['Tonk','Rajasthan','Central Rajasthan Commerce Hub'],
  ['Chittorgarh','Rajasthan','Zinc & Heritage Hub'],
  ['Jaisalmer','Rajasthan','Desert Tourism & Renewable Hub'],
  ['Dausa','Rajasthan','NCR-Rajasthan Commerce Hub'],
  ['Nagaur','Rajasthan','Central Rajasthan Commerce Hub'],
  ['Hanumangarh','Rajasthan','Northwest Rajasthan Commerce Hub'],
  ['Barmer','Rajasthan','Rajasthan Border Oil Commerce Hub'],
  ['Sawai Madhopur','Rajasthan','Rajasthan Wildlife Commerce Hub'],
  ['Bundi','Rajasthan','Rajasthan Heritage Commerce Hub'],
  ['Karauli','Rajasthan','Rajasthan Commerce Hub'],
  ['Dhaulpur','Rajasthan','Rajasthan Commerce Hub'],
  ['Rajsamand','Rajasthan','Rajasthan Marble Hub'],
  ['Banswara','Rajasthan','Rajasthan Tribal Commerce Hub'],
  ['Pratapgarh RJ','Rajasthan','Rajasthan Commerce Hub'],
  ['Dungarpur','Rajasthan','Rajasthan Tribal Commerce Hub'],
  ['Jalor','Rajasthan','Rajasthan Commerce Hub'],
  ['Sirohi','Rajasthan','Rajasthan Commerce Hub'],

  // ─── INDIA: GUJARAT ───────────────────────────────────────────────────────
  ['Ahmedabad','Gujarat','Textile & Enterprise Capital of Gujarat'],
  ['Surat','Gujarat','Diamond & Textile Commerce Hub'],
  ['Vadodara','Gujarat','Industrial & Petrochemical Hub'],
  ['Rajkot','Gujarat','Engineering & Manufacturing Hub'],
  ['Gandhinagar','Gujarat','Gujarat Capital & IT Hub'],
  ['Bhavnagar','Gujarat','Ship Recycling & Trade Hub'],
  ['Jamnagar','Gujarat','Brass Capital & Petrochemical Hub'],
  ['Junagadh','Gujarat','Agri & Commerce Center'],
  ['Anand','Gujarat','Dairy Capital & AMUL Hub'],
  ['Gandhidham','Gujarat','Kutch Trade & Port Gateway'],
  ['Morbi','Gujarat','Ceramic & Clock Industry Hub'],
  ['Navsari','Gujarat','South Gujarat Commerce Center'],
  ['Surendranagar','Gujarat','Cotton Belt Commerce Hub'],
  ['Mehsana','Gujarat','North Gujarat Industrial Hub'],
  ['Vapi','Gujarat','South Gujarat Chemical Zone'],
  ['Amreli','Gujarat','Saurashtra Commerce Hub'],
  ['Porbandar','Gujarat','Gujarat Coastal Commerce Hub'],
  ['Valsad','Gujarat','South Gujarat Industrial Hub'],
  ['Patan','Gujarat','North Gujarat Heritage Commerce Hub'],
  ['Bharuch','Gujarat','Gulf of Khambhat Industrial Hub'],
  ['Himmatnagar','Gujarat','North Gujarat Commerce Hub'],
  ['Godhra','Gujarat','Gujarat Central Commerce Hub'],
  ['Dahod','Gujarat','Gujarat Tribal Commerce Hub'],
  ['Navsari GJ','Gujarat','South Gujarat Heritage Hub'],
  ['Veraval','Gujarat','Gujarat Coastal Fishing Hub'],

  // ─── INDIA: KARNATAKA ─────────────────────────────────────────────────────
  ['Bangalore','Karnataka','Silicon Valley of India'],
  ['Bengaluru','Karnataka','Silicon Valley of India'],
  ['Mysuru','Karnataka','Tech & Cultural Heritage Hub'],
  ['Hubballi','Karnataka','North Karnataka Industrial Hub'],
  ['Mangaluru','Karnataka','Port & Educational Hub'],
  ['Belagavi','Karnataka','Border Region Commerce Hub'],
  ['Davangere','Karnataka','Cotton & Commerce Belt'],
  ['Ballari','Karnataka','Iron & Steel Hub'],
  ['Shivamogga','Karnataka','Malnad Regional Commerce Hub'],
  ['Kalaburagi','Karnataka','Hyderabad-Karnataka Commerce Hub'],
  ['Tumakuru','Karnataka','Bangalore Satellite Industrial Hub'],
  ['Raichur','Karnataka','Power & Agriculture Hub'],
  ['Bidar','Karnataka','Bidar Craft Heritage City'],
  ['Udupi','Karnataka','Coastal Trade & Education Hub'],
  ['Vijayapura','Karnataka','Northern Heritage Hub'],
  ['Dharwad','Karnataka','North Karnataka Education Hub'],
  ['Hassan','Karnataka','Karnataka Coffee Commerce Hub'],
  ['Mandya','Karnataka','Karnataka Sugar Commerce Hub'],
  ['Chikkamagaluru','Karnataka','Coffee & Plantation Commerce Hub'],
  ['Kolar','Karnataka','Bangalore Peripheral Commerce Hub'],
  ['Chitradurga','Karnataka','Karnataka Central Commerce Hub'],
  ['Bagalkot','Karnataka','Karnataka Commerce Hub'],
  ['Koppal','Karnataka','Karnataka Commerce Hub'],
  ['Haveri','Karnataka','Karnataka Commerce Hub'],
  ['Gadag','Karnataka','Karnataka Commerce Hub'],
  ['Chamarajanagar','Karnataka','Karnataka Southern Commerce Hub'],

  // ─── INDIA: TAMIL NADU ────────────────────────────────────────────────────
  ['Chennai','Tamil Nadu','Automotive & SaaS Capital'],
  ['Coimbatore','Tamil Nadu','Manchester of South India'],
  ['Madurai','Tamil Nadu','Temple City Commerce Hub'],
  ['Trichy','Tamil Nadu','Engineering & Education Hub'],
  ['Salem','Tamil Nadu','Steel & Textile Center'],
  ['Tirunelveli','Tamil Nadu','Southern TN Trade Hub'],
  ['Tiruppur','Tamil Nadu','Knitwear Export Capital'],
  ['Erode','Tamil Nadu','Turmeric & Textile Hub'],
  ['Vellore','Tamil Nadu','Healthcare & Education Hub'],
  ['Thoothukudi','Tamil Nadu','Port City & Pearl Trade Hub'],
  ['Thanjavur','Tamil Nadu','Rice Bowl & Heritage Hub'],
  ['Dindigul','Tamil Nadu','Lock & Commerce Hub'],
  ['Kanchipuram','Tamil Nadu','Temple & Silk Weaving City'],
  ['Nagercoil','Tamil Nadu','Southernmost TN Commerce Hub'],
  ['Hosur','Tamil Nadu','Bangalore Border Industrial Hub'],
  ['Cuddalore','Tamil Nadu','TN Industrial Corridor Hub'],
  ['Pudukkottai','Tamil Nadu','TN Central Commerce Hub'],
  ['Ramanathapuram','Tamil Nadu','TN Southern Commerce Hub'],
  ['Sivaganga','Tamil Nadu','TN Cultural Commerce Hub'],
  ['Virudhunagar','Tamil Nadu','TN Cracker Commerce Hub'],
  ['Krishnagiri','Tamil Nadu','TN Border Commerce Hub'],
  ['Namakkal','Tamil Nadu','TN Egg Capital Commerce Hub'],
  ['Nagapattinam','Tamil Nadu','TN Coastal Commerce Hub'],
  ['Tiruvallur','Tamil Nadu','Chennai Metropolitan Hub'],
  ['Villupuram','Tamil Nadu','TN Commerce Hub'],
  ['Ariyalur','Tamil Nadu','TN Cement Commerce Hub'],
  ['Perambalur','Tamil Nadu','TN Commerce Hub'],
  ['Karur','Tamil Nadu','TN Textile Commerce Hub'],
  ['Tiruvannamalai','Tamil Nadu','TN Pilgrimage Commerce Hub'],
  ['Dharmapuri','Tamil Nadu','TN Commerce Hub'],

  // ─── INDIA: ANDHRA PRADESH & TELANGANA ────────────────────────────────────
  ['Hyderabad','Telangana','IT & Pharma Capital'],
  ['Secunderabad','Telangana','Telangana Twin Commerce City'],
  ['Warangal','Telangana','Telangana Second City'],
  ['Nizamabad','Telangana','Northern Telangana Commerce'],
  ['Karimnagar','Telangana','Telangana Granite Trade Hub'],
  ['Khammam','Telangana','Telangana Coal Commerce Hub'],
  ['Mahbubnagar','Telangana','Telangana Southern Commerce Hub'],
  ['Nalgonda','Telangana','Telangana Commerce Hub'],
  ['Adilabad','Telangana','Telangana Northern Tribal Hub'],
  ['Suryapet','Telangana','Telangana Eastern Commerce Hub'],
  ['Visakhapatnam','Andhra Pradesh','Coastal Port & Tech Hub'],
  ['Vijayawada','Andhra Pradesh','AP Commerce & Trade Capital'],
  ['Guntur','Andhra Pradesh','AP Tobacco Commerce Hub'],
  ['Nellore','Andhra Pradesh','AP Southern Commerce Center'],
  ['Kurnool','Andhra Pradesh','Rayalaseema Commerce Center'],
  ['Rajahmundry','Andhra Pradesh','Godavari Delta Trade Hub'],
  ['Tirupati','Andhra Pradesh','Pilgrimage & Education Hub'],
  ['Eluru','Andhra Pradesh','AP Western Delta Commerce Hub'],
  ['Ongole','Andhra Pradesh','Prakasam Commerce Hub'],
  ['Anantapur','Andhra Pradesh','AP Western Industrial Hub'],
  ['Kadapa','Andhra Pradesh','Rayalaseema Commerce Hub'],
  ['Chittoor','Andhra Pradesh','AP Border Commerce Hub'],
  ['Srikakulam','Andhra Pradesh','AP Northern Coastal Hub'],
  ['Vizianagaram','Andhra Pradesh','AP Northern Heritage Hub'],
  ['Bhimavaram','Andhra Pradesh','AP Aquaculture Commerce Hub'],
  ['Kakinada','Andhra Pradesh','AP Eastern Port Commerce Hub'],

  // ─── INDIA: WEST BENGAL & EASTERN INDIA ──────────────────────────────────
  ['Kolkata','West Bengal','Eastern Business Gateway of India'],
  ['Howrah','West Bengal','Industrial & Engineering Hub'],
  ['Durgapur','West Bengal','Steel City of West Bengal'],
  ['Asansol','West Bengal','Coal & Industry Belt'],
  ['Siliguri','West Bengal','Northeast Gateway & Tea Trade'],
  ['Burdwan','West Bengal','WB Commerce Hub'],
  ['Malda','West Bengal','WB Northern Commerce Hub'],
  ['Barasat','West Bengal','Greater Kolkata Northern Hub'],
  ['Kalyani','West Bengal','WB Academic Industry Hub'],
  ['Kharagpur','West Bengal','WB Engineering Hub'],
  ['Haldia','West Bengal','WB Petrochemical Port Hub'],
  ['Jalpaiguri','West Bengal','WB Tea Commerce Hub'],
  ['Cooch Behar','West Bengal','WB Northern Commerce Hub'],
  ['Krishnanagar','West Bengal','WB Commerce Hub'],
  ['Patna','Bihar','Bihar State Capital Commerce Hub'],
  ['Gaya','Bihar','Bihar Religious Commerce Hub'],
  ['Muzaffarpur','Bihar','Bihar Northern Commerce Hub'],
  ['Bhagalpur','Bihar','Bihar Eastern Silk Hub'],
  ['Darbhanga','Bihar','Bihar Northern Commerce Hub'],
  ['Bihar Sharif','Bihar','Bihar Central Commerce Hub'],
  ['Purnia','Bihar','Bihar Eastern Commerce Hub'],
  ['Arrah','Bihar','Bihar Western Commerce Hub'],
  ['Begusarai','Bihar','Bihar Industrial Commerce Hub'],
  ['Katihar','Bihar','Bihar Eastern Corridor Hub'],
  ['Motihari','Bihar','Bihar Northern Commerce Hub'],
  ['Sitamarhi','Bihar','Bihar Northern Commerce Hub'],
  ['Madhubani','Bihar','Bihar Cultural Commerce Hub'],
  ['Saharsa','Bihar','Bihar Eastern Commerce Hub'],
  ['Siwan','Bihar','Bihar Western Commerce Hub'],
  ['Chapra','Bihar','Bihar Commerce Hub'],
  ['Hajipur','Bihar','Bihar Commerce Hub'],
  ['Ranchi','Jharkhand','Jharkhand Capital Mining Hub'],
  ['Jamshedpur','Jharkhand','Steel & Heavy Manufacturing City'],
  ['Dhanbad','Jharkhand','Coal Capital of India'],
  ['Bokaro','Jharkhand','Jharkhand Steel Hub'],
  ['Hazaribag','Jharkhand','Jharkhand Commerce Hub'],
  ['Giridih','Jharkhand','Jharkhand Mica Commerce Hub'],
  ['Deoghar','Jharkhand','Jharkhand Pilgrimage Commerce Hub'],
  ['Phusro','Jharkhand','Jharkhand Commerce Hub'],
  ['Bhubaneswar','Odisha','Odisha Capital & IT Hub'],
  ['Cuttack','Odisha','Odisha Silver Filigree Commerce'],
  ['Rourkela','Odisha','Odisha Steel Industrial City'],
  ['Berhampur','Odisha','Silk Commerce Hub of Odisha'],
  ['Sambalpur','Odisha','Odisha Western Commerce Hub'],
  ['Balasore','Odisha','Odisha Northern Commerce Hub'],
  ['Baripada','Odisha','Odisha Northern Commerce Hub'],
  ['Puri','Odisha','Odisha Pilgrimage Commerce Hub'],
  ['Brahmapur','Odisha','Odisha Southern Commerce Hub'],
  ['Bhadrak','Odisha','Odisha Commerce Hub'],

  // ─── INDIA: NCR & HARYANA & PUNJAB ───────────────────────────────────────
  ['Delhi','Delhi','National Capital Territory'],
  ['Delhi NCR','Delhi','National Capital Region Hub'],
  ['Gurgaon','Haryana','Corporate & Startup Capital'],
  ['Faridabad','Haryana','NCR Southern Industrial Belt'],
  ['Sonipat','Haryana','NCR Northern Manufacturing Hub'],
  ['Rohtak','Haryana','Haryana Healthcare Education Hub'],
  ['Panipat','Haryana','Haryana Textile Recycling Hub'],
  ['Hisar','Haryana','Haryana Steel Agriculture Hub'],
  ['Karnal','Haryana','Haryana Agri Dairy Hub'],
  ['Ambala','Haryana','Haryana Electronics Trade Hub'],
  ['Bhiwani','Haryana','Haryana Sports Commerce Hub'],
  ['Sirsa','Haryana','Haryana Western Agriculture Hub'],
  ['Yamunanagar','Haryana','Haryana Industrial Commerce Hub'],
  ['Palwal','Haryana','NCR Southeast Commerce Hub'],
  ['Rewari','Haryana','Haryana NCR Corridor Hub'],
  ['Nuh','Haryana','Haryana Southern Commerce Hub'],
  ['Kurukshetra','Haryana','Haryana Heritage Commerce Hub'],
  ['Jind','Haryana','Haryana Commerce Hub'],
  ['Kaithal','Haryana','Haryana Commerce Hub'],
  ['Panchkula','Haryana','Chandigarh Metropolitan Hub'],
  ['Ludhiana','Punjab','Punjab Industrial Textile Capital'],
  ['Amritsar','Punjab','Border Commerce Heritage Hub'],
  ['Jalandhar','Punjab','Sports Goods Industrial Hub'],
  ['Chandigarh','Punjab/Haryana','Tri-City Hub'],
  ['Patiala','Punjab','Heritage Agricultural Hub'],
  ['Bathinda','Punjab','Southwest Punjab Petrochemical Hub'],
  ['Pathankot','Punjab','Punjab Northern Gateway City'],
  ['Mohali','Punjab','Chandigarh Satellite IT Hub'],
  ['Zirakpur','Punjab','Chandigarh Peripheral Commerce Hub'],
  ['Hoshiarpur','Punjab','Punjab Commerce Hub'],
  ['Gurdaspur','Punjab','Punjab Northern Border Hub'],
  ['Moga','Punjab','Punjab Commerce Hub'],
  ['Kapurthala','Punjab','Punjab Heritage Commerce Hub'],
  ['Sangrur','Punjab','Punjab Commerce Hub'],
  ['Barnala','Punjab','Punjab Cotton Commerce Hub'],
  ['Fatehgarh Sahib','Punjab','Punjab Commerce Hub'],
  ['Faridkot','Punjab','Punjab Commerce Hub'],
  ['Mansa PB','Punjab','Punjab Commerce Hub'],

  // ─── INDIA: MADHYA PRADESH & CHHATTISGARH ────────────────────────────────
  ['Indore','Madhya Pradesh','MP Commerce & IT Capital'],
  ['Bhopal','Madhya Pradesh','MP State Capital District'],
  ['Jabalpur','Madhya Pradesh','MP Defense & Education Hub'],
  ['Gwalior','Madhya Pradesh','MP Heritage Trade District'],
  ['Ujjain','Madhya Pradesh','Religious Commerce Hub'],
  ['Sagar','Madhya Pradesh','Central MP Commerce District'],
  ['Rewa','Madhya Pradesh','MP Eastern Commerce Hub'],
  ['Satna','Madhya Pradesh','MP Cement Mining Hub'],
  ['Ratlam','Madhya Pradesh','MP Railway Commerce Hub'],
  ['Dewas','Madhya Pradesh','MP Industrial Cluster'],
  ['Katni','Madhya Pradesh','MP Limestone Railway Hub'],
  ['Singrauli','Madhya Pradesh','MP Coal Power Hub'],
  ['Chhindwara','Madhya Pradesh','MP Agri Commerce Hub'],
  ['Bhind','Madhya Pradesh','MP Northern Commerce Hub'],
  ['Morena','Madhya Pradesh','MP Northern Commerce Hub'],
  ['Guna','Madhya Pradesh','MP Central Commerce Hub'],
  ['Shivpuri','Madhya Pradesh','MP Northern Commerce Hub'],
  ['Betul','Madhya Pradesh','MP Commerce Hub'],
  ['Hoshangabad','Madhya Pradesh','MP Commerce Hub'],
  ['Vidisha','Madhya Pradesh','MP Commerce Hub'],
  ['Sehore','Madhya Pradesh','MP Commerce Hub'],
  ['Mandla','Madhya Pradesh','MP Commerce Hub'],
  ['Seoni','Madhya Pradesh','MP Commerce Hub'],
  ['Balaghat','Madhya Pradesh','MP Commerce Hub'],
  ['Raipur','Chhattisgarh','Chhattisgarh Capital Industry'],
  ['Bhilai','Chhattisgarh','CG Steel City'],
  ['Bilaspur','Chhattisgarh','CG Railway Commerce Hub'],
  ['Durg','Chhattisgarh','CG Industrial Belt Hub'],
  ['Korba','Chhattisgarh','CG Power Capital'],
  ['Rajnandgaon','Chhattisgarh','CG Commerce Hub'],
  ['Raigarh','Chhattisgarh','CG Coal Commerce Hub'],
  ['Jagdalpur','Chhattisgarh','CG Southern Commerce Hub'],
  ['Ambikapur','Chhattisgarh','CG Northern Commerce Hub'],

  // ─── INDIA: KERALA ────────────────────────────────────────────────────────
  ['Kochi','Kerala','Kerala Maritime Tech Capital'],
  ['Thiruvananthapuram','Kerala','Kerala IT Governance Hub'],
  ['Kozhikode','Kerala','Malabar Commerce Spice Hub'],
  ['Thrissur','Kerala','Kerala Cultural Finance Hub'],
  ['Kannur','Kerala','North Kerala Weaving Trade'],
  ['Palakkad','Kerala','Kerala Gateway City'],
  ['Malappuram','Kerala','Kerala Northern Commerce Hub'],
  ['Alappuzha','Kerala','Backwaters Tourism Coir Hub'],
  ['Kollam','Kerala','Cashew Marine Products Hub'],
  ['Kottayam','Kerala','Rubber Education Capital'],
  ['Pathanamthitta','Kerala','Kerala Pilgrim Commerce Hub'],
  ['Idukki','Kerala','Kerala Plantation Hub'],
  ['Wayanad','Kerala','Kerala Forest Plantation Hub'],
  ['Kasaragod','Kerala','North Kerala Border Commerce Hub'],

  // ─── INDIA: NORTHEAST & OTHERS ───────────────────────────────────────────
  ['Guwahati','Assam','Northeast Commerce Gateway'],
  ['Dibrugarh','Assam','Assam Tea Oil Capital'],
  ['Silchar','Assam','Barak Valley Commerce Hub'],
  ['Jorhat','Assam','Assam Tea Commerce Hub'],
  ['Nagaon','Assam','Assam Central Commerce Hub'],
  ['Tinsukia','Assam','Assam Commerce Hub'],
  ['Bongaigaon','Assam','Assam Commerce Hub'],
  ['Shillong','Meghalaya','Scotland of the East Hub'],
  ['Tura','Meghalaya','Meghalaya Commerce Hub'],
  ['Imphal','Manipur','Northeast Cultural Capital'],
  ['Agartala','Tripura','Tripura Capital Gateway'],
  ['Itanagar','Arunachal Pradesh','Northeast Frontier Hub'],
  ['Kohima','Nagaland','Nagaland Capital Commerce Hub'],
  ['Dimapur','Nagaland','Nagaland Commerce Hub'],
  ['Aizawl','Mizoram','Mizoram Capital Commerce Hub'],
  ['Lunglei','Mizoram','Mizoram Commerce Hub'],
  ['Gangtok','Sikkim','Sikkim Capital Tourism Hub'],
  ['Dehradun','Uttarakhand','Uttarakhand Capital IT Hub'],
  ['Haridwar','Uttarakhand','Pilgrim Pharma Industry Hub'],
  ['Haldwani','Uttarakhand','Kumaon Gateway Commerce Hub'],
  ['Roorkee','Uttarakhand','Uttarakhand Engineering Hub'],
  ['Rishikesh','Uttarakhand','Yoga Wellness Commerce Hub'],
  ['Kashipur','Uttarakhand','Uttarakhand Commerce Hub'],
  ['Rudrapur','Uttarakhand','Uttarakhand Industrial Hub'],
  ['Jammu','J&K','J&K Winter Capital Commerce Hub'],
  ['Srinagar','J&K','J&K Summer Capital Crafts Hub'],
  ['Anantnag','J&K','Kashmir Valley Commerce Hub'],
  ['Udhampur','J&K','J&K Commerce Hub'],
  ['Shimla','Himachal Pradesh','Himachal Capital Tourism Hub'],
  ['Dharamshala','Himachal Pradesh','HP Tourism Commerce Hub'],
  ['Mandi','Himachal Pradesh','HP Commerce Hub'],
  ['Solan','Himachal Pradesh','HP Industrial Commerce Hub'],
  ['Bilaspur HP','Himachal Pradesh','HP Commerce Hub'],
  ['Baddi','Himachal Pradesh','HP Pharmaceutical Hub'],
  ['Goa','Goa','Coastal Tourism Startup Hub'],
  ['Panaji','Goa','Goa Capital Tourism Commerce'],
  ['Margao','Goa','Goa Southern Commerce Hub'],
  ['Vasco da Gama','Goa','Goa Port Commerce Hub'],
  ['Pondicherry','Puducherry','French Heritage Commerce Hub'],
  ['Karaikal','Puducherry','Puducherry Commerce Hub'],

  // ─── MORE INDIA: REMAINING DISTRICTS & TOWNS ──────────────────────────────
  // UP remaining
  ['Kannauj','Uttar Pradesh','UP Commerce Hub'],
  ['Jaunpur','Uttar Pradesh','UP Commerce Hub'],
  ['Ghazipur','Uttar Pradesh','UP Commerce Hub'],
  ['Chandauli','Uttar Pradesh','UP Commerce Hub'],
  ['Sonbhadra','Uttar Pradesh','UP Mineral Commerce Hub'],
  ['Pratapgarh UP','Uttar Pradesh','UP Commerce Hub'],
  ['Rae Bareli','Uttar Pradesh','UP Commerce Hub'],
  ['Amethi','Uttar Pradesh','UP Commerce Hub'],
  ['Faizabad','Uttar Pradesh','UP Ayodhya Commerce Hub'],
  ['Ambedkar Nagar','Uttar Pradesh','UP Commerce Hub'],
  ['Bijnor','Uttar Pradesh','UP Commerce Hub'],
  ['Pilibhit','Uttar Pradesh','UP Commerce Hub'],
  ['Lakhimpur Kheri','Uttar Pradesh','UP Commerce Hub'],
  ['Barabanki','Uttar Pradesh','UP Commerce Hub'],
  ['Baghpat','Uttar Pradesh','UP NCR Commerce Hub'],
  ['Muzaffarnagar UP','Uttar Pradesh','UP Commerce Hub'],
  ['Shamli','Uttar Pradesh','UP Commerce Hub'],
  ['Kasganj','Uttar Pradesh','UP Commerce Hub'],
  ['Agra Rural','Uttar Pradesh','UP Commerce Hub'],
  ['Hathras','Uttar Pradesh','UP Commerce Hub'],
  // Bihar remaining
  ['Aurangabad BR','Bihar','Bihar Commerce Hub'],
  ['Munger','Bihar','Bihar Commerce Hub'],
  ['Jehanabad','Bihar','Bihar Commerce Hub'],
  ['Arwal','Bihar','Bihar Commerce Hub'],
  ['Nalanda','Bihar','Bihar Commerce Hub'],
  ['Nawada','Bihar','Bihar Commerce Hub'],
  ['Jamui','Bihar','Bihar Commerce Hub'],
  ['Lakhisarai','Bihar','Bihar Commerce Hub'],
  ['Sheikhpura','Bihar','Bihar Commerce Hub'],
  ['Banka','Bihar','Bihar Commerce Hub'],
  ['Supaul','Bihar','Bihar Commerce Hub'],
  ['Madhepura','Bihar','Bihar Commerce Hub'],
  ['Khagaria','Bihar','Bihar Commerce Hub'],
  ['Araria','Bihar','Bihar Commerce Hub'],
  ['Kishanganj','Bihar','Bihar Northeast Commerce Hub'],
  ['Gopalganj','Bihar','Bihar Commerce Hub'],
  ['Saran','Bihar','Bihar Commerce Hub'],
  ['Vaishali','Bihar','Bihar Heritage Commerce Hub'],
  ['East Champaran','Bihar','Bihar Commerce Hub'],
  ['West Champaran','Bihar','Bihar Commerce Hub'],
  // Rajasthan remaining
  ['Jalore','Rajasthan','Rajasthan Commerce Hub'],
  ['Pali RJ','Rajasthan','Rajasthan Commerce Hub'],
  ['Sirohi','Rajasthan','Rajasthan Commerce Hub'],
  ['Baran','Rajasthan','Rajasthan Commerce Hub'],
  ['Jhalawar','Rajasthan','Rajasthan Commerce Hub'],
  ['Kota Rural','Rajasthan','Rajasthan Commerce Hub'],
  ['Jhunjhunu','Rajasthan','Rajasthan Commerce Hub'],
  ['Churu','Rajasthan','Rajasthan Commerce Hub'],
  // Gujarat remaining
  ['Botad','Gujarat','Gujarat Commerce Hub'],
  ['Kheda','Gujarat','Gujarat Commerce Hub'],
  ['Ankleshwar','Gujarat','Gujarat Chemical Commerce Hub'],
  ['Dholka','Gujarat','Gujarat Commerce Hub'],
  ['Halvad','Gujarat','Gujarat Commerce Hub'],
  ['Unjha','Gujarat','Gujarat Seed Commerce Hub'],
  // Karnataka remaining
  ['Yadgir','Karnataka','Karnataka Commerce Hub'],
  ['Haveri','Karnataka','Karnataka Commerce Hub'],
  ['Gadag','Karnataka','Karnataka Commerce Hub'],
  ['Bagalkot','Karnataka','Karnataka Commerce Hub'],
  ['Chamrajanagar','Karnataka','Karnataka Commerce Hub'],
  ['Kodagu','Karnataka','Karnataka Coffee Heritage Hub'],
  // Tamil Nadu remaining
  ['Kallakurichi','Tamil Nadu','TN Commerce Hub'],
  ['Ranipet','Tamil Nadu','TN Commerce Hub'],
  ['Tirupathur','Tamil Nadu','TN Commerce Hub'],
  ['Chengalpattu','Tamil Nadu','TN Commerce Hub'],
  ['Tenkasi','Tamil Nadu','TN Commerce Hub'],
  ['Mayiladuthurai','Tamil Nadu','TN Commerce Hub'],
  // Odisha remaining
  ['Angul','Odisha','Odisha Commerce Hub'],
  ['Dhenkanal','Odisha','Odisha Commerce Hub'],
  ['Keonjhar','Odisha','Odisha Mining Commerce Hub'],
  ['Kendujhar','Odisha','Odisha Commerce Hub'],
  ['Jajpur','Odisha','Odisha Commerce Hub'],
  ['Bhuban','Odisha','Odisha Commerce Hub'],
  ['Jeypore','Odisha','Odisha Commerce Hub'],
  ['Koraput','Odisha','Odisha Commerce Hub'],
  // West Bengal remaining
  ['Bardhaman','West Bengal','WB Commerce Hub'],
  ['Bankura','West Bengal','WB Commerce Hub'],
  ['Purulia','West Bengal','WB Commerce Hub'],
  ['Birbhum','West Bengal','WB Commerce Hub'],
  ['Murshidabad','West Bengal','WB Commerce Hub'],
  ['Nadia','West Bengal','WB Commerce Hub'],
  ['North 24 Parganas','West Bengal','WB Commerce Hub'],
  ['South 24 Parganas','West Bengal','WB Commerce Hub'],
  // Assam remaining
  ['Lakhimpur AS','Assam','Assam Commerce Hub'],
  ['Dhemaji','Assam','Assam Commerce Hub'],
  ['Sonitpur','Assam','Assam Commerce Hub'],
  ['Kamrup','Assam','Assam Commerce Hub'],
  ['Cachar','Assam','Assam Commerce Hub'],
  ['Karbi Anglong','Assam','Assam Commerce Hub'],
  // MP remaining
  ['Narsinghpur','Madhya Pradesh','MP Commerce Hub'],
  ['Chhattarpur','Madhya Pradesh','MP Commerce Hub'],
  ['Damoh','Madhya Pradesh','MP Commerce Hub'],
  ['Panna','Madhya Pradesh','MP Diamond Commerce Hub'],
  ['Tikamgarh','Madhya Pradesh','MP Commerce Hub'],
  ['Datia','Madhya Pradesh','MP Commerce Hub'],
  ['Ashoknagar','Madhya Pradesh','MP Commerce Hub'],
  ['Guna MP','Madhya Pradesh','MP Commerce Hub'],
  // Telangana remaining
  ['Bhadradri Kothagudem','Telangana','Telangana Commerce Hub'],
  ['Jagtial','Telangana','Telangana Commerce Hub'],
  ['Jangaon','Telangana','Telangana Commerce Hub'],
  ['Jayashankar','Telangana','Telangana Commerce Hub'],
  ['Jogulamba Gadwal','Telangana','Telangana Commerce Hub'],
  ['Kamareddy','Telangana','Telangana Commerce Hub'],
  ['Mancherial','Telangana','Telangana Commerce Hub'],
  ['Medak','Telangana','Telangana Commerce Hub'],
  ['Medchal','Telangana','Hyderabad Metropolitan Hub'],
  ['Mulugu','Telangana','Telangana Commerce Hub'],
  ['Nagarkurnool','Telangana','Telangana Commerce Hub'],
  ['Nalgonda TG','Telangana','Telangana Commerce Hub'],
  ['Narayanpet','Telangana','Telangana Commerce Hub'],
  ['Nirmal','Telangana','Telangana Commerce Hub'],
  ['Peddapalli','Telangana','Telangana Commerce Hub'],
  ['Rajanna Sircilla','Telangana','Telangana Commerce Hub'],
  ['Rangareddy','Telangana','Hyderabad Metropolitan Hub'],
  ['Sangareddy','Telangana','Telangana Commerce Hub'],
  ['Siddipet','Telangana','Telangana Commerce Hub'],
  ['Vikarabad','Telangana','Telangana Commerce Hub'],
  ['Wanaparthy','Telangana','Telangana Commerce Hub'],
  ['Yadadri','Telangana','Telangana Commerce Hub'],
  // AP remaining
  ['Alluri Sitharama Raju','Andhra Pradesh','AP Commerce Hub'],
  ['Anakapalli','Andhra Pradesh','AP Commerce Hub'],
  ['Bapatla','Andhra Pradesh','AP Commerce Hub'],
  ['Konaseema','Andhra Pradesh','AP Coastal Commerce Hub'],
  ['Manyam','Andhra Pradesh','AP Tribal Commerce Hub'],
  ['Nandyal','Andhra Pradesh','AP Commerce Hub'],
  ['NTR District','Andhra Pradesh','AP Commerce Hub'],
  ['Palnadu','Andhra Pradesh','AP Commerce Hub'],
  ['Prakasam','Andhra Pradesh','AP Commerce Hub'],
  ['Sri Balaji','Andhra Pradesh','AP Commerce Hub'],
  ['Sri Satya Sai','Andhra Pradesh','AP Commerce Hub'],
  // Kerala remaining
  ['Ernakulam','Kerala','Kerala Commerce Hub'],
  ['Thrissur Rural','Kerala','Kerala Commerce Hub'],
  ['Palakkad Rural','Kerala','Kerala Commerce Hub'],
  // Uttarakhand remaining
  ['Almora','Uttarakhand','Uttarakhand Commerce Hub'],
  ['Bageshwar','Uttarakhand','Uttarakhand Commerce Hub'],
  ['Chamoli','Uttarakhand','Uttarakhand Commerce Hub'],
  ['Champawat','Uttarakhand','Uttarakhand Commerce Hub'],
  ['Nainital','Uttarakhand','Uttarakhand Tourism Commerce Hub'],
  ['Pithoragarh','Uttarakhand','Uttarakhand Commerce Hub'],
  ['Tehri','Uttarakhand','Uttarakhand Commerce Hub'],
  ['Udham Singh Nagar','Uttarakhand','Uttarakhand Industrial Hub'],
  ['Uttarkashi','Uttarakhand','Uttarakhand Commerce Hub'],
  ['Pauri Garhwal','Uttarakhand','Uttarakhand Commerce Hub'],
  // Himachal remaining
  ['Una HP','Himachal Pradesh','HP Commerce Hub'],
  ['Sirmaur','Himachal Pradesh','HP Commerce Hub'],
  ['Hamirpur HP','Himachal Pradesh','HP Commerce Hub'],
  ['Kangra','Himachal Pradesh','HP Commerce Hub'],
  ['Kullu','Himachal Pradesh','HP Tourism Commerce Hub'],
  ['Lahaul Spiti','Himachal Pradesh','HP High Altitude Commerce Hub'],
  ['Kinnaur','Himachal Pradesh','HP Apple Commerce Hub'],
  ['Chamba','Himachal Pradesh','HP Commerce Hub'],

  // ─── MORE GLOBAL: ADDITIONAL CITIES ────────────────────────────────────────
  // More Europe
  ['Dusseldorf DE','Germany','Germany Fashion Commerce Hub'],
  ['Mainz','Germany','Germany Media Commerce Hub'],
  ['Freiburg','Germany','Germany Southwest Commerce Hub'],
  ['Heidelberg','Germany','Germany Academic Commerce Hub'],
  ['Kassel','Germany','Germany Commerce Hub'],
  ['Erfurt','Germany','Germany Central Commerce Hub'],
  ['Rostock','Germany','Germany Baltic Commerce Hub'],
  ['Saarbrucken','Germany','Germany Commerce Hub'],
  ['Chemnitz','Germany','Germany Commerce Hub'],
  ['Munster','Germany','Germany Commerce Hub'],
  ['Zaragoza','Spain','Spain Northeast Commerce Hub'],
  ['Cordoba SP','Spain','Spain Heritage Commerce Hub'],
  ['Valladolid','Spain','Spain Commerce Hub'],
  ['Pamplona','Spain','Spain Commerce Hub'],
  ['San Sebastian','Spain','Spain Basque Commerce Hub'],
  ['Salamanca','Spain','Spain Academic Commerce Hub'],
  ['Cadiz','Spain','Spain Commerce Hub'],
  ['Gijon','Spain','Spain Northern Commerce Hub'],
  ['Cartagena SP','Spain','Spain Mediterranean Commerce Hub'],
  ['Badajoz','Spain','Spain Commerce Hub'],
  ['Lyon FR','France','France Commerce Hub'],
  ['Clermont-Ferrand','France','France Commerce Hub'],
  ['Dijon','France','France Burgundy Commerce Hub'],
  ['Le Havre','France','France Port Commerce Hub'],
  ['Reims','France','France Champagne Commerce Hub'],
  ['Saint-Etienne','France','France Commerce Hub'],
  ['Metz','France','France Commerce Hub'],
  ['Amiens','France','France Commerce Hub'],
  ['Caen','France','France Normandy Commerce Hub'],
  ['Perpignan','France','France Mediterranean Commerce Hub'],
  ['Padova','Italy','Italy Commerce Hub'],
  ['Brescia','Italy','Italy Commerce Hub'],
  ['Trieste','Italy','Italy Port Commerce Hub'],
  ['Reggio Calabria','Italy','Italy Southern Commerce Hub'],
  ['Taranto','Italy','Italy Commerce Hub'],
  ['Salerno','Italy','Italy Commerce Hub'],
  ['Ferrara','Italy','Italy Commerce Hub'],
  ['Modena','Italy','Italy Motor Valley Hub'],
  ['Parma','Italy','Italy Food Commerce Hub'],
  ['Livorno','Italy','Italy Port Commerce Hub'],
  ['Pisa','Italy','Italy Commerce Hub'],
  ['Perugia','Italy','Italy Commerce Hub'],
  ['Catanzaro','Italy','Italy Commerce Hub'],
  ['Reggio Emilia','Italy','Italy Commerce Hub'],
  // More UK
  ['Portsmouth','United Kingdom','UK Commerce Hub'],
  ['Exeter','United Kingdom','UK Southwest Commerce Hub'],
  ['Cambridge','United Kingdom','UK Academic Commerce Hub'],
  ['Oxford','United Kingdom','UK Academic Commerce Hub'],
  ['Aberdeen','United Kingdom','UK Oil Commerce Hub'],
  ['Dundee','United Kingdom','UK Scotland Commerce Hub'],
  ['Swansea','United Kingdom','UK Wales Commerce Hub'],
  ['Plymouth','United Kingdom','UK Commerce Hub'],
  ['Derby','United Kingdom','UK Commerce Hub'],
  ['Hull','United Kingdom','UK Port Commerce Hub'],
  ['Middlesbrough','United Kingdom','UK Commerce Hub'],
  ['Sunderland','United Kingdom','UK Commerce Hub'],
  ['Ipswich','United Kingdom','UK Commerce Hub'],
  ['Luton','United Kingdom','UK Commerce Hub'],
  ['Reading','United Kingdom','UK Commerce Hub'],
  ['Milton Keynes','United Kingdom','UK Commerce Hub'],
  ['Peterborough','United Kingdom','UK Commerce Hub'],
  ['Northampton','United Kingdom','UK Commerce Hub'],
  ['York','United Kingdom','UK Heritage Commerce Hub'],
  ['Bournemouth','United Kingdom','UK Commerce Hub'],
  // More Africa
  ['Ibadan NG','Nigeria','Nigeria Oyo Commerce Hub'],
  ['Oyo','Nigeria','Nigeria Commerce Hub'],
  ['Ondo','Nigeria','Nigeria Commerce Hub'],
  ['Ekiti','Nigeria','Nigeria Commerce Hub'],
  ['Kwara','Nigeria','Nigeria Commerce Hub'],
  ['Niger State','Nigeria','Nigeria Commerce Hub'],
  ['Sokoto','Nigeria','Nigeria Northwest Commerce Hub'],
  ['Katsina','Nigeria','Nigeria Commerce Hub'],
  ['Kebbi','Nigeria','Nigeria Commerce Hub'],
  ['Zamfara','Nigeria','Nigeria Commerce Hub'],
  ['Jigawa','Nigeria','Nigeria Commerce Hub'],
  ['Bauchi','Nigeria','Nigeria Commerce Hub'],
  ['Gombe','Nigeria','Nigeria Commerce Hub'],
  ['Yobe','Nigeria','Nigeria Commerce Hub'],
  ['Taraba','Nigeria','Nigeria Commerce Hub'],
  ['Adamawa','Nigeria','Nigeria Commerce Hub'],
  ['Benue','Nigeria','Nigeria Commerce Hub'],
  ['Kogi','Nigeria','Nigeria Commerce Hub'],
  ['Nasarawa','Nigeria','Nigeria Commerce Hub'],
  ['Plateau','Nigeria','Nigeria Commerce Hub'],
  ['Thika KE','Kenya','Kenya Commerce Hub'],
  ['Machakos','Kenya','Kenya Commerce Hub'],
  ['Nyeri','Kenya','Kenya Central Commerce Hub'],
  ['Meru KE','Kenya','Kenya Commerce Hub'],
  ['Kitale','Kenya','Kenya Commerce Hub'],
  ['Nyahururu','Kenya','Kenya Commerce Hub'],
  ['Malindi','Kenya','Kenya Coastal Commerce Hub'],
  ['Kakamega','Kenya','Kenya Western Commerce Hub'],
  ['Kisii','Kenya','Kenya Commerce Hub'],
  ['Kericho','Kenya','Kenya Tea Commerce Hub'],
  ['Thika RD','Kenya','Kenya Commerce Hub'],
  ['Johannesburg South','South Africa','SA Commerce Hub'],
  ['Tshwane','South Africa','SA Metro Commerce Hub'],
  ['Ekurhuleni','South Africa','SA East Rand Commerce Hub'],
  ['Mangaung','South Africa','SA Free State Hub'],
  ['eThekwini','South Africa','SA KZN Metro Hub'],
  ['Buffalo City','South Africa','SA Eastern Cape Hub'],
  ['Nelson Mandela Bay','South Africa','SA Eastern Cape Hub'],
  ['Limpopo','South Africa','SA Northern Commerce Hub'],
  ['Temba','South Africa','SA Commerce Hub'],
  ['Mafikeng','South Africa','SA Commerce Hub'],
  ['Rustenburg','South Africa','SA Platinum Commerce Hub'],
  ['Witbank','South Africa','SA Coal Commerce Hub'],
  ['Kimberley','South Africa','SA Diamond Commerce Hub'],
  ['George','South Africa','SA Garden Route Hub'],
  ['Pietermaritzburg','South Africa','SA KZN Commerce Hub'],
  ['Richards Bay','South Africa','SA Port Commerce Hub'],
  ['Empangeni','South Africa','SA Commerce Hub'],
  ['Benoni','South Africa','SA Commerce Hub'],
  ['Boksburg','South Africa','SA Commerce Hub'],
  ['Sebokeng','South Africa','SA Commerce Hub'],
  ['Vereeniging','South Africa','SA Commerce Hub'],
  // More East Africa
  ['Jinja','Uganda','Uganda Commerce Hub'],
  ['Fort Portal','Uganda','Uganda Commerce Hub'],
  ['Masaka','Uganda','Uganda Commerce Hub'],
  ['Soroti','Uganda','Uganda Commerce Hub'],
  ['Lira','Uganda','Uganda Commerce Hub'],
  ['Arua','Uganda','Uganda Commerce Hub'],
  ['Mbale','Uganda','Uganda Commerce Hub'],
  ['Butebo','Uganda','Uganda Commerce Hub'],
  ['Moshi','Tanzania','Tanzania Kilimanjaro Commerce Hub'],
  ['Tanga','Tanzania','Tanzania Port Commerce Hub'],
  ['Mbeya','Tanzania','Tanzania Southern Commerce Hub'],
  ['Morogoro','Tanzania','Tanzania Commerce Hub'],
  ['Iringa','Tanzania','Tanzania Commerce Hub'],
  ['Songea','Tanzania','Tanzania Commerce Hub'],
  ['Shinyanga','Tanzania','Tanzania Commerce Hub'],
  ['Tabora','Tanzania','Tanzania Commerce Hub'],
  ['Kigoma','Tanzania','Tanzania Western Commerce Hub'],
  ['Musoma','Tanzania','Tanzania Lake Victoria Hub'],
  ['Bujumbura BI','Burundi','Burundi Port Commerce Hub'],
  // More West Africa
  ['Abomey-Calavi','Benin','Benin Commerce Hub'],
  ['Parakou','Benin','Benin Commerce Hub'],
  ['Lome LR','Togo','Togo Commerce Hub'],
  ['Tsevie','Togo','Togo Commerce Hub'],
  ['Banjul','Gambia','Gambia Commerce Capital'],
  ['Serekunda','Gambia','Gambia Commerce Hub'],
  ['Bissau','Guinea-Bissau','Guinea-Bissau Commerce Hub'],
  ['Bata EG','Equatorial Guinea','EG Commerce Hub'],
  ['Malabo','Equatorial Guinea','EG Commerce Capital'],
  ['Ebolowa','Cameroon','Cameroon Commerce Hub'],
  ['Bafoussam','Cameroon','Cameroon Commerce Hub'],
  ['Bamenda','Cameroon','Cameroon Commerce Hub'],
  ['Buea','Cameroon','Cameroon Commerce Hub'],
  ['Kumba','Cameroon','Cameroon Commerce Hub'],
  ['Ngaoundere','Cameroon','Cameroon Commerce Hub'],
  ['Garoua','Cameroon','Cameroon Commerce Hub'],
  ['Maroua','Cameroon','Cameroon Commerce Hub'],
  // More Southern Africa
  ['Lilongwe LW','Malawi','Malawi Commerce Hub'],
  ['Zombie','Malawi','Malawi Commerce Hub'],
  ['Mzuzu','Malawi','Malawi Commerce Hub'],
  ['Kasungu','Malawi','Malawi Commerce Hub'],
  ['Lusaka LZ','Zambia','Zambia Commerce Hub'],
  ['Livingstone','Zambia','Zambia Tourism Commerce Hub'],
  ['Chingola','Zambia','Zambia Commerce Hub'],
  ['Kabwe','Zambia','Zambia Commerce Hub'],
  ['Harare HZ','Zimbabwe','Zimbabwe Commerce Hub'],
  ['Mutare','Zimbabwe','Zimbabwe Commerce Hub'],
  ['Gweru','Zimbabwe','Zimbabwe Commerce Hub'],
  ['Kwekwe','Zimbabwe','Zimbabwe Commerce Hub'],
  ['Chinhoyi','Zimbabwe','Zimbabwe Commerce Hub'],
  // More SEA
  ['Kota Kinabalu MY','Malaysia','Malaysia Sabah Commerce Hub'],
  ['Sandakan','Malaysia','Malaysia Commerce Hub'],
  ['Tawau','Malaysia','Malaysia Commerce Hub'],
  ['Miri','Malaysia','Malaysia Sarawak Commerce Hub'],
  ['Sibu','Malaysia','Malaysia Commerce Hub'],
  ['Bintulu','Malaysia','Malaysia Commerce Hub'],
  ['Sungai Petani','Malaysia','Malaysia Commerce Hub'],
  ['Taiping','Malaysia','Malaysia Commerce Hub'],
  ['Seremban SB','Malaysia','Malaysia Commerce Hub'],
  ['Klang','Malaysia','Malaysia Port Commerce Hub'],
  ['Subang Jaya','Malaysia','Malaysia Commerce Hub'],
  ['Ampang','Malaysia','Malaysia Commerce Hub'],
  ['Puchong','Malaysia','Malaysia Commerce Hub'],
  ['Kajang','Malaysia','Malaysia Commerce Hub'],
  ['Seri Kembangan','Malaysia','Malaysia Commerce Hub'],
  ['Cirebon','Indonesia','Indonesia West Java Commerce Hub'],
  ['Sukabumi','Indonesia','Indonesia West Java Commerce Hub'],
  ['Tasikmalaya','Indonesia','Indonesia West Java Commerce Hub'],
  ['Serang','Indonesia','Indonesia Banten Commerce Hub'],
  ['Bogor','Indonesia','Indonesia Bogor Commerce Hub'],
  ['Bekasi','Indonesia','Indonesia Commerce Hub'],
  ['Tangerang Selatan','Indonesia','Indonesia Commerce Hub'],
  ['Cilegon','Indonesia','Indonesia Commerce Hub'],
  ['Purwokerto','Indonesia','Indonesia Central Java Hub'],
  ['Tegal','Indonesia','Indonesia Commerce Hub'],
  ['Pekalongan','Indonesia','Indonesia Batik Commerce Hub'],
  ['Salatiga','Indonesia','Indonesia Commerce Hub'],
  ['Magelang','Indonesia','Indonesia Commerce Hub'],
  ['Kudus','Indonesia','Indonesia Commerce Hub'],
  ['Jepara','Indonesia','Indonesia Furniture Commerce Hub'],
  ['Blitar','Indonesia','Indonesia Commerce Hub'],
  ['Kediri','Indonesia','Indonesia Commerce Hub'],
  ['Madiun','Indonesia','Indonesia Commerce Hub'],
  ['Mojokerto','Indonesia','Indonesia Commerce Hub'],
  ['Probolinggo','Indonesia','Indonesia Commerce Hub'],
  ['Pasuruan','Indonesia','Indonesia Commerce Hub'],
  ['Jember','Indonesia','Indonesia Commerce Hub'],
  ['Situbondo','Indonesia','Indonesia Commerce Hub'],
  ['Lumajang','Indonesia','Indonesia Commerce Hub'],
  ['Banyuwangi','Indonesia','Indonesia Commerce Hub'],
  ['Singaraja','Indonesia','Bali North Commerce Hub'],
  ['Mataram','Indonesia','NTB Commerce Capital'],
  ['Kupang','Indonesia','NTT Commerce Capital'],
  ['Ambon','Indonesia','Maluku Commerce Capital'],
  ['Jayapura','Indonesia','Papua Commerce Capital'],
  ['Sorong','Indonesia','Papua Barat Commerce Hub'],
  // More Bangladesh
  ['Bogra','Bangladesh','Bangladesh Commerce Hub'],
  ['Mymensingh','Bangladesh','Bangladesh Commerce Hub'],
  ['Tangail','Bangladesh','Bangladesh Commerce Hub'],
  ['Dinajpur','Bangladesh','Bangladesh Commerce Hub'],
  ['Pabna','Bangladesh','Bangladesh Commerce Hub'],
  ['Jessore','Bangladesh','Bangladesh Commerce Hub'],
  ['Barisal BR','Bangladesh','Bangladesh Commerce Hub'],
  ['Noakhali','Bangladesh','Bangladesh Commerce Hub'],
  ['Feni','Bangladesh','Bangladesh Commerce Hub'],
  ['Brahmanbaria','Bangladesh','Bangladesh Commerce Hub'],
  ['Cox\'s Bazar','Bangladesh','Bangladesh Tourism Commerce Hub'],
  // More Pakistan
  ['Sialkot','Pakistan','Pakistan Surgical Commerce Hub'],
  ['Bahawalpur','Pakistan','Pakistan Commerce Hub'],
  ['Sargodha','Pakistan','Pakistan Commerce Hub'],
  ['Gujrat PK','Pakistan','Pakistan Furniture Commerce Hub'],
  ['Sheikhupura PK','Pakistan','Pakistan Commerce Hub'],
  ['Sukkur','Pakistan','Pakistan Sindh Commerce Hub'],
  ['Larkana','Pakistan','Pakistan Commerce Hub'],
  ['Rahim Yar Khan','Pakistan','Pakistan Commerce Hub'],
  ['Sahiwal','Pakistan','Pakistan Commerce Hub'],
  ['Okara','Pakistan','Pakistan Commerce Hub'],
  ['Kasur','Pakistan','Pakistan Commerce Hub'],
  ['Nawabshah','Pakistan','Pakistan Commerce Hub'],
  ['Mardan','Pakistan','Pakistan Commerce Hub'],
  ['Abbottabad','Pakistan','Pakistan Commerce Hub'],
  ['Mingora','Pakistan','Pakistan Commerce Hub'],
  // More Central Asia
  ['Namangan','Uzbekistan','Uzbekistan Commerce Hub'],
  ['Andijan','Uzbekistan','Uzbekistan Commerce Hub'],
  ['Fergana','Uzbekistan','Uzbekistan Commerce Hub'],
  ['Bukhara','Uzbekistan','Uzbekistan Heritage Commerce Hub'],
  ['Nukus','Uzbekistan','Uzbekistan Commerce Hub'],
  ['Karaganda','Kazakhstan','Kazakhstan Commerce Hub'],
  ['Aktobe','Kazakhstan','Kazakhstan Commerce Hub'],
  ['Pavlodar','Kazakhstan','Kazakhstan Commerce Hub'],
  ['Oskemen','Kazakhstan','Kazakhstan Commerce Hub'],
  ['Semey','Kazakhstan','Kazakhstan Commerce Hub'],
  ['Sumqayit','Azerbaijan','Azerbaijan Commerce Hub'],
  ['Ganja AZ','Azerbaijan','Azerbaijan Commerce Hub'],
  ['Rustavi','Georgia','Georgia Commerce Hub'],
  ['Batumi','Georgia','Georgia Commerce Hub'],
  ['Gyumri','Armenia','Armenia Commerce Hub'],
  // More East Asia
  ['Harbin CN','China','China Northern Commerce Hub'],
  ['Lanzhou','China','China Northwest Commerce Hub'],
  ['Hohhot','China','China Inner Mongolia Hub'],
  ['Baotou','China','China Commerce Hub'],
  ['Shijiazhuang','China','China Commerce Hub'],
  ['Tangshan','China','China Steel Commerce Hub'],
  ['Weifang','China','China Commerce Hub'],
  ['Zibo','China','China Commerce Hub'],
  ['Linyi','China','China Commerce Hub'],
  ['Jining','China','China Commerce Hub'],
  ['Dezhou','China','China Commerce Hub'],
  ['Yantai','China','China Commerce Hub'],
  ['Nantong','China','China Commerce Hub'],
  ['Wuxi','China','China Commerce Hub'],
  ['Suzhou','China','China Commerce Hub'],
  ['Changzhou','China','China Commerce Hub'],
  ['Yangzhou','China','China Commerce Hub'],
  ['Zhenjiang','China','China Commerce Hub'],
  ['Nanchang NC','China','China Commerce Hub'],
  ['Jiujiang','China','China Commerce Hub'],
  ['Wenzhou','China','China Commerce Hub'],
  ['Zhuhai','China','China Commerce Hub'],
  ['Dongguan','China','China Commerce Hub'],
  ['Foshan','China','China Commerce Hub'],
  ['Zhuzhou','China','China Commerce Hub'],
  ['Hengyang','China','China Commerce Hub'],
  ['Luoyang','China','China Commerce Hub'],
  ['Nanyang','China','China Commerce Hub'],
  ['Xinxiang','China','China Commerce Hub'],
  ['Anyang','China','China Commerce Hub'],
  ['Xianyang','China','China Commerce Hub'],
  ['Baoji','China','China Commerce Hub'],
  ['Yinchuan','China','China Ningxia Hub'],
  ['Xining','China','China Qinghai Hub'],
  ['Anshan','China','China Commerce Hub'],
  ['Fushun','China','China Commerce Hub'],
  ['Benxi','China','China Commerce Hub'],
  ['Dandong','China','China Border Commerce Hub'],
  ['Jinzhou','China','China Commerce Hub'],
  // More Japan
  ['Niigata','Japan','Japan Commerce Hub'],
  ['Hamamatsu','Japan','Japan Commerce Hub'],
  ['Sagamihara','Japan','Japan Commerce Hub'],
  ['Chiba','Japan','Japan Commerce Hub'],
  ['Saitama','Japan','Japan Commerce Hub'],
  ['Okayama','Japan','Japan Commerce Hub'],
  ['Kumamoto','Japan','Japan Commerce Hub'],
  ['Kagoshima','Japan','Japan Commerce Hub'],
  ['Matsuyama','Japan','Japan Commerce Hub'],
  ['Takamatsu','Japan','Japan Commerce Hub'],
  ['Tokushima','Japan','Japan Commerce Hub'],
  ['Naha','Japan','Okinawa Commerce Hub'],
  // More South Korea
  ['Jeonju','South Korea','Korea Commerce Hub'],
  ['Cheongju','South Korea','Korea Commerce Hub'],
  ['Chuncheon','South Korea','Korea Commerce Hub'],
  ['Wonju','South Korea','Korea Commerce Hub'],
  ['Changwon','South Korea','Korea Commerce Hub'],
  ['Jinju','South Korea','Korea Commerce Hub'],
  ['Pohang','South Korea','Korea Steel Commerce Hub'],
  ['Andong','South Korea','Korea Commerce Hub'],
  ['Gumi','South Korea','Korea Electronics Hub'],
  // More LatAm cities
  ['Boa Vista BR','Brazil','Brazil Roraima Commerce Hub'],
  ['Rio Branco','Brazil','Brazil Acre Commerce Hub'],
  ['Porto Velho BR','Brazil','Brazil Commerce Hub'],
  ['Macapa BR','Brazil','Brazil Amapa Commerce Hub'],
  ['Palmas BR','Brazil','Brazil Tocantins Commerce Hub'],
  ['Maringa','Brazil','Brazil Parana Commerce Hub'],
  ['Londrina','Brazil','Brazil Parana Commerce Hub'],
  ['Joinville','Brazil','Brazil Santa Catarina Hub'],
  ['Blumenau','Brazil','Brazil Santa Catarina Hub'],
  ['Caxias do Sul','Brazil','Brazil Rio Grande do Sul Hub'],
  ['Pelotas','Brazil','Brazil Commerce Hub'],
  ['Uberlandia','Brazil','Brazil Minas Gerais Commerce Hub'],
  ['Contagem','Brazil','Brazil Minas Gerais Commerce Hub'],
  ['Juiz de Fora','Brazil','Brazil Commerce Hub'],
  ['Ribeirao Preto','Brazil','Brazil Sao Paulo Commerce Hub'],
  ['Sao Jose dos Campos','Brazil','Brazil Technology Hub'],
  ['Santo Andre','Brazil','Brazil ABC Commerce Hub'],
  ['Sao Bernardo','Brazil','Brazil Commerce Hub'],
  ['Osasco','Brazil','Brazil Commerce Hub'],
  ['Guarulhos','Brazil','Brazil Commerce Hub'],
  ['Diadema','Brazil','Brazil Commerce Hub'],
  ['Sao Jose do Rio Preto','Brazil','Brazil Commerce Hub'],
  ['Sorocaba','Brazil','Brazil Commerce Hub'],
  ['Bauru','Brazil','Brazil Commerce Hub'],
  ['Jundiai','Brazil','Brazil Commerce Hub'],
  ['Piracicaba','Brazil','Brazil Commerce Hub'],
  ['Limeira','Brazil','Brazil Commerce Hub'],
  ['Franca','Brazil','Brazil Shoes Commerce Hub'],
  ['Araraquara','Brazil','Brazil Commerce Hub'],
  ['Americana','Brazil','Brazil Commerce Hub'],
  ['Medellin MX','Colombia','Colombia Commerce Hub'],
  ['Barranquilla CO','Colombia','Colombia Commerce Hub'],
  ['Pereira CO','Colombia','Colombia Commerce Hub'],
  ['Armenia CO','Colombia','Colombia Commerce Hub'],
  ['Manizales CO','Colombia','Colombia Commerce Hub'],
  ['Villavicencio','Colombia','Colombia Commerce Hub'],
  ['Pasto','Colombia','Colombia Commerce Hub'],
  ['Monteria','Colombia','Colombia Commerce Hub'],
  ['Valledupar','Colombia','Colombia Commerce Hub'],
  ['Sincelejo','Colombia','Colombia Commerce Hub'],
  ['Neiva','Colombia','Colombia Commerce Hub'],
  ['Ibague CO','Colombia','Colombia Commerce Hub'],
  ['Popayan','Colombia','Colombia Commerce Hub'],
  ['Buenaventura','Colombia','Colombia Port Commerce Hub'],
  ['Palmira','Colombia','Colombia Commerce Hub'],
  ['Tunja','Colombia','Colombia Commerce Hub'],
  ['Santa Marta','Colombia','Colombia Tourism Commerce Hub'],
  ['Ica','Peru','Peru Commerce Hub'],
  ['Pucallpa','Peru','Peru Commerce Hub'],
  ['Huancayo','Peru','Peru Highlands Commerce Hub'],
  ['Cusco','Peru','Peru Tourism Commerce Hub'],
  ['Tacna','Peru','Peru Commerce Hub'],
  ['Puno','Peru','Peru Commerce Hub'],
  ['Juliaca','Peru','Peru Commerce Hub'],
  ['Chimbote','Peru','Peru Commerce Hub'],
  ['Ayacucho','Peru','Peru Commerce Hub'],
  ['Arica','Chile','Chile Northern Commerce Hub'],
  ['Rancagua','Chile','Chile Commerce Hub'],
  ['Talca','Chile','Chile Commerce Hub'],
  ['Linares','Chile','Chile Commerce Hub'],
  ['Chillan','Chile','Chile Commerce Hub'],
  ['Osorno','Chile','Chile Commerce Hub'],
  ['Puerto Montt','Chile','Chile Commerce Hub'],
  ['Punta Arenas','Chile','Chile Southernmost Commerce Hub'],
  ['Arica CL','Chile','Chile Commerce Hub'],
  ['La Serena','Chile','Chile Commerce Hub'],
  ['Coquimbo','Chile','Chile Commerce Hub'],
  ['Copiap','Chile','Chile Commerce Hub'],
  ['Calama','Chile','Chile Mining Commerce Hub'],
  ['Corrientes','Argentina','Argentina Commerce Hub'],
  ['Resistencia','Argentina','Argentina Commerce Hub'],
  ['Salta','Argentina','Argentina Commerce Hub'],
  ['San Miguel de Tucuman','Argentina','Argentina Commerce Hub'],
  ['Posadas','Argentina','Argentina Commerce Hub'],
  ['Neuquen','Argentina','Argentina Commerce Hub'],
  ['Santa Fe AR','Argentina','Argentina Commerce Hub'],
  ['Parana AR','Argentina','Argentina Commerce Hub'],
  ['Bahia Blanca','Argentina','Argentina Commerce Hub'],
  ['San Juan AR','Argentina','Argentina Commerce Hub'],
  ['San Luis AR','Argentina','Argentina Commerce Hub'],
  ['Rio Cuarto','Argentina','Argentina Commerce Hub'],
  ['San Rafael AR','Argentina','Argentina Commerce Hub'],
  ['Formosa','Argentina','Argentina Commerce Hub'],
  ['Jujuy','Argentina','Argentina Commerce Hub'],
  ['Catamarca','Argentina','Argentina Commerce Hub'],
  ['La Rioja AR','Argentina','Argentina Commerce Hub'],
  ['Santiago del Estero','Argentina','Argentina Commerce Hub'],
  ['Rawson','Argentina','Argentina Commerce Hub'],
  ['Comodoro Rivadavia','Argentina','Argentina Commerce Hub'],
  // More MENA / Africa horn
  ['Karbala','Iraq','Iraq Religious Commerce Hub'],
  ['Kirkuk','Iraq','Iraq Oil Commerce Hub'],
  ['Fallujah','Iraq','Iraq Commerce Hub'],
  ['Ramadi','Iraq','Iraq Commerce Hub'],
  ['Tikrit','Iraq','Iraq Commerce Hub'],
  ['Baqubah','Iraq','Iraq Commerce Hub'],
  ['Nasiriyah','Iraq','Iraq Commerce Hub'],
  ['Amarah','Iraq','Iraq Commerce Hub'],
  ['Diwaniyah','Iraq','Iraq Commerce Hub'],
  ['Hillah','Iraq','Iraq Commerce Hub'],
  ['Kut','Iraq','Iraq Commerce Hub'],
  ['Samawah','Iraq','Iraq Commerce Hub'],
  // More Myanmar
  ['Bago','Myanmar','Myanmar Commerce Hub'],
  ['Pathein','Myanmar','Myanmar Commerce Hub'],
  ['Mawlamyine','Myanmar','Myanmar Commerce Hub'],
  ['Pyay','Myanmar','Myanmar Commerce Hub'],
  ['Meiktila','Myanmar','Myanmar Commerce Hub'],
  ['Lashio','Myanmar','Myanmar Commerce Hub'],
  ['Myitkyina','Myanmar','Myanmar Commerce Hub'],
  // More Vietnam
  ['Thai Nguyen','Vietnam','Vietnam Commerce Hub'],
  ['Nam Dinh','Vietnam','Vietnam Commerce Hub'],
  ['Hue VN','Vietnam','Vietnam Heritage Commerce Hub'],
  ['Quang Ngai','Vietnam','Vietnam Commerce Hub'],
  ['Quy Nhon','Vietnam','Vietnam Commerce Hub'],
  ['Pleiku','Vietnam','Vietnam Commerce Hub'],
  ['Buon Me Thuot','Vietnam','Vietnam Commerce Hub'],
  ['Phan Thiet','Vietnam','Vietnam Commerce Hub'],
  ['Long Xuyen','Vietnam','Vietnam Commerce Hub'],
  ['Rach Gia','Vietnam','Vietnam Commerce Hub'],
  ['Ca Mau','Vietnam','Vietnam Commerce Hub'],
  ['My Tho','Vietnam','Vietnam Commerce Hub'],
  ['Ben Tre','Vietnam','Vietnam Commerce Hub'],
  ['Vinh','Vietnam','Vietnam Commerce Hub'],
  ['Hoa Binh','Vietnam','Vietnam Commerce Hub'],
  // More Philippines
  ['Zamboanga PH','Philippines','Philippines Commerce Hub'],
  ['Cotabato','Philippines','Philippines Commerce Hub'],
  ['Iligan','Philippines','Philippines Commerce Hub'],
  ['Butuan','Philippines','Philippines Commerce Hub'],
  ['Dumaguete','Philippines','Philippines Commerce Hub'],
  ['Bacolod','Philippines','Philippines Commerce Hub'],
  ['Naga','Philippines','Philippines Commerce Hub'],
  ['Legazpi','Philippines','Philippines Commerce Hub'],
  ['Tacloban','Philippines','Philippines Commerce Hub'],
  ['Ormoc','Philippines','Philippines Commerce Hub'],
  // More Thailand
  ['Rayong','Thailand','Thailand Commerce Hub'],
  ['Chonburi','Thailand','Thailand Commerce Hub'],
  ['Nakhon Si Thammarat','Thailand','Thailand Commerce Hub'],
  ['Surat Thani','Thailand','Thailand Commerce Hub'],
  ['Phitsanulok','Thailand','Thailand Commerce Hub'],
  ['Lampang','Thailand','Thailand Commerce Hub'],
  ['Nakhon Pathom','Thailand','Thailand Commerce Hub'],
  ['Samut Prakan','Thailand','Thailand Commerce Hub'],
  ['Pathum Thani','Thailand','Thailand Commerce Hub'],
  ['Ayutthaya','Thailand','Thailand Heritage Commerce Hub'],
  ['Mukdahan','Thailand','Thailand Mekong Commerce Hub'],
  ['Ubon Ratchathani','Thailand','Thailand Commerce Hub'],
  ['Khon Kaen TH','Thailand','Thailand Commerce Hub'],
  ['Nakhon Ratchasima TH','Thailand','Thailand Commerce Hub'],
  // More Sri Lanka
  ['Matara','Sri Lanka','Sri Lanka Commerce Hub'],
  ['Kurunegala','Sri Lanka','Sri Lanka Commerce Hub'],
  ['Anuradhapura','Sri Lanka','Sri Lanka Heritage Commerce Hub'],
  ['Polonnaruwa','Sri Lanka','Sri Lanka Commerce Hub'],
  ['Badulla','Sri Lanka','Sri Lanka Commerce Hub'],
  ['Ratnapura','Sri Lanka','Sri Lanka Gem Commerce Hub'],
  ['Trincomalee','Sri Lanka','Sri Lanka Commerce Hub'],
  ['Batticaloa','Sri Lanka','Sri Lanka Commerce Hub'],
  ['Ampara','Sri Lanka','Sri Lanka Commerce Hub'],
  // More Nepal
  ['Lalitpur','Nepal','Nepal Commerce Hub'],
  ['Bhaktapur','Nepal','Nepal Heritage Commerce Hub'],
  ['Dharan','Nepal','Nepal Commerce Hub'],
  ['Hetauda','Nepal','Nepal Commerce Hub'],
  ['Butwal','Nepal','Nepal Commerce Hub'],
  ['Pokhara NP','Nepal','Nepal Commerce Hub'],
  // More Mongolia
  ['Erdenet','Mongolia','Mongolia Commerce Hub'],
  ['Darkhan','Mongolia','Mongolia Commerce Hub'],
  // More Pacific
  ['Apia','Samoa','Pacific Island Commerce Hub'],
  ['Nuku\'alofa','Tonga','Pacific Island Commerce Hub'],
  ['Honiara','Solomon Islands','Pacific Island Commerce Hub'],
  ['Port Vila','Vanuatu','Pacific Island Commerce Hub'],
  ['Funafuti','Tuvalu','Pacific Island Commerce Hub'],
  ['Tarawa','Kiribati','Pacific Island Commerce Hub'],
  ['Koror','Palau','Pacific Island Commerce Hub'],
  // More Caribbean
  ['Fort-de-France','Martinique','Caribbean Commerce Hub'],
  ['Pointe-a-Pitre','Guadeloupe','Caribbean Commerce Hub'],
  ['Paramaribo','Suriname','South America Commerce Hub'],
  ['Georgetown GY','Guyana','South America Commerce Hub'],
  ['Cayenne','French Guiana','South America Commerce Hub'],
  ['Belize City BZ','Belize','Central America Commerce Hub'],
  ['Nassau BS','Bahamas','Caribbean Commerce Hub'],
  ['Hamilton BM','Bermuda','Atlantic Commerce Hub'],
  ['George Town KY','Cayman Islands','Caribbean Finance Hub'],
];

module.exports = { CITIES };
