// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const getEnv = (key: string) => {
  if (typeof process !== 'undefined' && process.env && process.env[key]) return process.env[key];
  if (typeof import.meta !== 'undefined' && (import.meta as any).env && (import.meta as any).env[key]) return (import.meta as any).env[key];
  return undefined;
};

const SUPABASE_URL = getEnv('VITE_SUPABASE_URL') || 'https://cenxckpxaqborfqyexot.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = getEnv('VITE_SUPABASE_PUBLISHABLE_KEY') || getEnv('VITE_SUPABASE_ANON_KEY') || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlbnhja3B4YXFib3JmcXlleG90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5NzU1NzQsImV4cCI6MjA5ODU1MTU3NH0.rCmVgQbMVIzG0h5nmDniHZpJtK9VUfW1mGO40VY_MZE';

// Resilient storage wrapper with memory fallback and cross-key recovery
const memoryStorage = new Map<string, string>();

const resilientStorage = {
  getItem: (key: string): string | null => {
    if (typeof window === 'undefined') return memoryStorage.get(key) || null;
    try {
      let val = window.localStorage.getItem(key);
      if (!val && key.includes('cenxckpxaqborfqyexot')) {
        // Fallback checks for legacy/generic stored sessions
        val = window.localStorage.getItem('sb-auth-token') || 
              window.localStorage.getItem('sb-sbayuqgomlflmxgicplz-auth-token');
        if (val) {
          try { 
            window.localStorage.setItem(key, val); 
          } catch (storageErr) {
            console.debug('[SupabaseStorage] Fallback key copy failed:', storageErr);
          }
        }
      }
      return val || memoryStorage.get(key) || null;
    } catch {
      return memoryStorage.get(key) || null;
    }
  },
  setItem: (key: string, value: string): void => {
    memoryStorage.set(key, value);
    if (typeof window !== 'undefined') {
      try {
        window.localStorage.setItem(key, value);
        // Also mirror generic key for cross-bridge compatibility
        window.localStorage.setItem('sb-auth-token', value);
      } catch (e) {
        console.warn('[SupabaseStorage] LocalStorage write failed, preserved in memory:', e);
      }
    }
  },
  removeItem: (key: string): void => {
    memoryStorage.delete(key);
    if (typeof window !== 'undefined') {
      try {
        window.localStorage.removeItem(key);
        window.localStorage.removeItem('sb-auth-token');
      } catch (removeErr) {
        console.debug('[SupabaseStorage] LocalStorage remove failed:', removeErr);
      }
    }
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: resilientStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
