// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const getEnv = (key: string) => {
  if (typeof process !== 'undefined' && process.env && process.env[key]) return process.env[key];
  if (typeof import.meta !== 'undefined' && (import.meta as any).env && (import.meta as any).env[key]) return (import.meta as any).env[key];
  return undefined;
};

const SUPABASE_URL = 'https://sbayuqgomlflmxgicplz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiYXl1cWdvbWxmbG14Z2ljcGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MTc2MDAsImV4cCI6MjA3NDk5MzYwMH0.gVSObpMtsv5W2nuLBHKT8G1_hXIprWXdn5l7Bnnj7jw';

// Resilient storage wrapper with memory fallback
const memoryStorage = new Map<string, string>();

// One-time cleanup of poisoned legacy tokens
if (typeof window !== 'undefined') {
  try {
    const poisonedKeys = [
      'sb-cenxckpxaqborfqyexot-auth-token',
      'sb-auth-token'
    ];
    for (const key of poisonedKeys) {
      if (window.localStorage.getItem(key)) {
        window.localStorage.removeItem(key);
      }
    }
  } catch (e) {
    console.debug('[SupabaseStorage] Cleanup failed:', e);
  }
}

const resilientStorage = {
  getItem: (key: string): string | null => {
    if (typeof window === 'undefined') return memoryStorage.get(key) || null;
    try {
      const val = window.localStorage.getItem(key);
      // If token contains a synthetic/invalid marker, purge it immediately to prevent refresh loops
      if (val && val.includes('chatr_synthetic_refresh_')) {
        window.localStorage.removeItem(key);
        memoryStorage.delete(key);
        return null;
      }
      return val || memoryStorage.get(key) || null;
    } catch {
      return memoryStorage.get(key) || null;
    }
  },
  setItem: (key: string, value: string): void => {
    memoryStorage.set(key, value);
    if (typeof window !== 'undefined') {
      try {
        window.localStorage.setItem(key, value);
      } catch (e) {
        console.warn('[SupabaseStorage] LocalStorage write failed, preserved in memory:', e);
      }
    }
  },
  removeItem: (key: string): void => {
    memoryStorage.delete(key);
    if (typeof window !== 'undefined') {
      try {
        window.localStorage.removeItem(key);
        window.localStorage.removeItem('sb-auth-token');
        window.localStorage.removeItem('sb-sbayuqgomlflmxgicplz-auth-token');
      } catch (removeErr) {
        console.debug('[SupabaseStorage] LocalStorage remove failed:', removeErr);
      }
    }
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: resilientStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
