/**
 * CHATR AI Training Infrastructure
 * src/services/ai/SoupTrainingClient.ts
 *
 * Dedicated TypeScript client for the Soup training worker running on Colab/Kaggle T4.
 * This is SEPARATE from VideoGenerationWorker.ts (different concerns, different endpoints).
 *
 * Training worker runs alongside the video worker on the same Colab notebook,
 * but uses completely independent FastAPI routes.
 */

export type TrainingMethod = 'sft' | 'dpo' | 'orpo';
export type SoupShipVerdictResult = 'SHIP' | 'DONT_SHIP' | 'UNKNOWN';

export type ChatrCapability =
  | 'general' | 'coding' | 'reasoning' | 'business' | 'finance'
  | 'seo' | 'marketing' | 'creator' | 'video' | 'research'
  | 'support' | 'agent' | 'rag' | 'meera';

// ============================================================
// REQUEST / RESPONSE TYPES
// ============================================================

export interface TrainingJobPlan {
  capability: ChatrCapability;
  baseModel: string;
  method: TrainingMethod;
  datasetId: string;
  datasetVersion?: string;
  maxSeqLen?: number;
  batchSize?: number;
  gradientAccumulationSteps?: number;
  learningRate?: number;
  loraRank?: number;
  loraAlpha?: number;
  seed?: number;
  budgetMinutes?: number;
  humanApprovedBy?: string;
  humanApprovedAt?: string;
  notes?: string;
}

export type TrainingJobState =
  | 'QUEUED'
  | 'SOUP_TRAINING'
  | 'SOUP_EVALUATING'
  | 'SHIP_VERDICT_READY'
  | 'DOWNLOADING_ADAPTER'
  | 'COMPLETED'
  | 'FAILED';

export interface TrainingJobStatus {
  jobId: string;
  state: TrainingJobState;
  progressPercent: number;
  capability: string;
  method: string;
  currentEpoch?: number;
  totalEpochs?: number;
  currentLoss?: number;
  tokensPerSec?: number;
  peakVramGb?: number;
  elapsedMinutes?: number;
  estimatedRemainingMinutes?: number;
  error?: string;
}

export interface SoupShipEvidence {
  capabilityScore: number;
  regressionScore: number;
  safetyScore: number;
  toolUseScore?: number;
  jsonValidityScore?: number;
  peakVramGb?: number;
  tokPerSec?: number;
}

export interface SoupShipVerdict {
  verdict: SoupShipVerdictResult;
  jobId: string;
  capability: string;
  evidence: SoupShipEvidence;
  emittedAt: string;
  soupVersion: string;
}

export interface TrainingWorkerHealth {
  status: 'ONLINE' | 'OFFLINE' | 'DEGRADED';
  gpuName: string;
  vramTotalGb: number;
  vramFreeGb: number;
  soupVersion?: string;
  activeJob?: string;
  backend: 'COLAB_T4' | 'KAGGLE_T4' | 'LOCAL_CUDA';
}

export interface AdapterRecord {
  capability: ChatrCapability;
  version: string;
  status: 'PRODUCTION' | 'EVALUATING' | 'ARCHIVED' | 'REJECTED';
  baseModel: string;
  method: TrainingMethod;
  datasetId: string;
  soupVerdict: SoupShipVerdictResult;
  chatrGate: 'PASS' | 'FAIL' | 'PENDING';
  ollamaModelName: string;
  promotedAt?: string;
  promotedBy?: string;
}

// ============================================================
// SOUP TRAINING CLIENT
// ============================================================

export class SoupTrainingClient {
  private endpoint: string;

  constructor(endpoint = 'http://localhost:8000') {
    this.endpoint = endpoint.replace(/\/$/, '');
  }

  setEndpoint(url: string): void {
    this.endpoint = url.replace(/\/$/, '');
  }

  /** Check training worker health. */
  async healthCheck(): Promise<TrainingWorkerHealth> {
    try {
      const res = await fetch(`${this.endpoint}/training-health`, {
        signal: AbortSignal.timeout(5000),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.json();
    } catch (err: any) {
      return {
        status: 'OFFLINE',
        gpuName: 'Unknown',
        vramTotalGb: 0,
        vramFreeGb: 0,
        backend: 'COLAB_T4',
      };
    }
  }

  /**
   * Submit a training job to the Soup worker.
   * The dataset is sent as base64 — the worker writes it to /content/chatr_datasets/.
   * The locked soup.yaml is generated by the Python SoupJobController on the Dell;
   * this client just transmits the approved plan + encoded data.
   */
  async submitTrainingJob(
    plan: TrainingJobPlan,
    datasetB64: string,
    evalDatasetB64?: string,
    configB64?: string,
    policyHash?: string
  ): Promise<{ jobId: string; state: string }> {
    const res = await fetch(`${this.endpoint}/train`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        capability: plan.capability,
        base_model: plan.baseModel,
        method: plan.method,
        dataset_id: plan.datasetId,
        dataset_b64: datasetB64,
        eval_b64: evalDatasetB64 ?? '',
        config_b64: configB64 ?? '',
        policy_hash: policyHash ?? '',
        lora_rank: plan.loraRank ?? 16,
        lora_alpha: plan.loraAlpha ?? 32,
        max_seq_len: plan.maxSeqLen ?? 1024,
        batch_size: plan.batchSize ?? 4,
        seed: plan.seed ?? 1234,
      }),
    });
    if (!res.ok) throw new Error(`Training submission failed: HTTP ${res.status}`);
    return res.json();
  }

  /** Poll training job status. */
  async getTrainingStatus(jobId: string): Promise<TrainingJobStatus> {
    const res = await fetch(`${this.endpoint}/train-status/${jobId}`, {
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) throw new Error(`Status check failed: HTTP ${res.status}`);
    return res.json();
  }

  /** Get Soup's `soup ship` verdict for a completed training job. */
  async getShipVerdict(jobId: string): Promise<SoupShipVerdict> {
    const res = await fetch(`${this.endpoint}/ship-verdict/${jobId}`, {
      signal: AbortSignal.timeout(15000),
    });
    if (!res.ok) throw new Error(`Ship verdict failed: HTTP ${res.status}`);
    return res.json();
  }

  /** Download the trained adapter as a Blob (.safetensors zip). */
  async downloadAdapter(jobId: string): Promise<Blob> {
    const res = await fetch(`${this.endpoint}/download-adapter/${jobId}`, {
      signal: AbortSignal.timeout(120000),
    });
    if (!res.ok) throw new Error(`Adapter download failed: HTTP ${res.status}`);
    return res.blob();
  }

  /** Cancel a running training job. */
  async cancelJob(jobId: string): Promise<{ success: boolean }> {
    const res = await fetch(`${this.endpoint}/cancel-job/${jobId}`, {
      method: 'POST',
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) return { success: false };
    return res.json();
  }

  /** Get training logs tail for a job. */
  async getTrainingLogs(jobId: string, tailLines = 50): Promise<string[]> {
    const res = await fetch(`${this.endpoint}/train-logs/${jobId}?tail=${tailLines}`, {
      signal: AbortSignal.timeout(10000),
    });
    if (!res.ok) return [];
    const data = await res.json();
    return data.lines ?? [];
  }
}
